export enum GraphQLErrorCode {
  // Subscription errors
  SUBSCRIPTION_EXPIRED = 'SUBSCRIPTION_EXPIRED',
  SUBSCRIPTION_INVALID = 'SUBSCRIPTION_INVALID',
  SUBSCRIPTION_VERIFICATION_FAILED = 'SUBSCRIPTION_VERIFICATION_FAILED',

  // Voice errors
  VOICE_NOT_READY = 'VOICE_NOT_READY',
  VOICE_QUOTA_EXCEEDED = 'VOICE_QUOTA_EXCEEDED',
  VOICE_PROFILE_NOT_FOUND = 'VOICE_PROFILE_NOT_FOUND',

  // Narration errors
  NARRATION_NOT_CACHED = 'NARRATION_NOT_CACHED',
  NARRATION_GENERATION_FAILED = 'NARRATION_GENERATION_FAILED',

  // Auth errors
  TOKEN_INVALID = 'TOKEN_INVALID',
  USER_NOT_FOUND = 'USER_NOT_FOUND',

  // Rate limiting
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',

  // Push notification errors
  DEVICE_TOKEN_INVALID = 'DEVICE_TOKEN_INVALID',
  NOTIFICATION_FAILED = 'NOTIFICATION_FAILED',
}
