import { PrismaClient } from '@prisma/client';
import { Pool } from 'pg';
import { PrismaPg } from '@prisma/adapter-pg';
import 'dotenv/config';

const connectionString = process.env.DATABASE_URL;
const pool = new Pool({ connectionString });
const adapter = new PrismaPg(pool);

const prisma = new PrismaClient({
  adapter,
  log: ['error', 'warn'],
});

async function main() {
  console.log('🌱 Seeding ingredient catalog...');

  const ingredients = [
    // DAIRY (~20 entries)
    {
      canonicalName: 'eggs',
      canonicalNameTR: 'yumurta',
      aliases: ['egg', 'large eggs', 'whole eggs', 'yumurtalar'],
      defaultCategory: 'dairy',
      defaultShelfLifeDays: 30,
    },
    {
      canonicalName: 'milk',
      canonicalNameTR: 'süt',
      aliases: ['whole milk', '2% milk', 'skim milk', 'tam yağlı süt', 'yağsız süt'],
      defaultCategory: 'dairy',
      defaultShelfLifeDays: 7,
    },
    {
      canonicalName: 'butter',
      canonicalNameTR: 'tereyağı',
      aliases: ['unsalted butter', 'salted butter', 'tuzlu tereyağı', 'tuzsuz tereyağı'],
      defaultCategory: 'dairy',
      defaultShelfLifeDays: 60,
    },
    {
      canonicalName: 'cheese',
      canonicalNameTR: 'peynir',
      aliases: ['cheddar', 'mozzarella', 'parmesan', 'kaşar peyniri', 'tulum peyniri'],
      defaultCategory: 'dairy',
      defaultShelfLifeDays: 30,
    },
    {
      canonicalName: 'yogurt',
      canonicalNameTR: 'yoğurt',
      aliases: ['greek yogurt', 'plain yogurt', 'süzme yoğurt'],
      defaultCategory: 'dairy',
      defaultShelfLifeDays: 14,
    },
    {
      canonicalName: 'cream',
      canonicalNameTR: 'krema',
      aliases: ['heavy cream', 'whipping cream', 'çırpma kremasi'],
      defaultCategory: 'dairy',
      defaultShelfLifeDays: 7,
    },
    {
      canonicalName: 'sour cream',
      canonicalNameTR: 'ekşi krema',
      aliases: ['soured cream'],
      defaultCategory: 'dairy',
      defaultShelfLifeDays: 14,
    },
    {
      canonicalName: 'cream cheese',
      canonicalNameTR: 'krem peynir',
      aliases: ['philadelphia'],
      defaultCategory: 'dairy',
      defaultShelfLifeDays: 21,
    },
    {
      canonicalName: 'mozzarella',
      canonicalNameTR: 'mozzarella',
      aliases: ['fresh mozzarella', 'mozzarella peyniri'],
      defaultCategory: 'dairy',
      defaultShelfLifeDays: 14,
    },
    {
      canonicalName: 'parmesan',
      canonicalNameTR: 'parmesan',
      aliases: ['parmigiano reggiano', 'parmesan peyniri'],
      defaultCategory: 'dairy',
      defaultShelfLifeDays: 60,
    },
    {
      canonicalName: 'cheddar',
      canonicalNameTR: 'çedar',
      aliases: ['cheddar cheese', 'sharp cheddar', 'çedar peyniri'],
      defaultCategory: 'dairy',
      defaultShelfLifeDays: 30,
    },
    {
      canonicalName: 'feta',
      canonicalNameTR: 'beyaz peynir',
      aliases: ['feta cheese', 'beyaz peynir'],
      defaultCategory: 'dairy',
      defaultShelfLifeDays: 21,
    },
    {
      canonicalName: 'ricotta',
      canonicalNameTR: 'ricotta',
      aliases: ['ricotta cheese', 'ricotta peyniri'],
      defaultCategory: 'dairy',
      defaultShelfLifeDays: 7,
    },
    {
      canonicalName: 'cottage cheese',
      canonicalNameTR: 'lor peyniri',
      aliases: ['cottage', 'lor'],
      defaultCategory: 'dairy',
      defaultShelfLifeDays: 10,
    },
    {
      canonicalName: 'whipped cream',
      canonicalNameTR: 'çırpılmış krema',
      aliases: ['chantilly', 'şanti'],
      defaultCategory: 'dairy',
      defaultShelfLifeDays: 7,
    },
    {
      canonicalName: 'condensed milk',
      canonicalNameTR: 'yoğunlaştırılmış süt',
      aliases: ['sweetened condensed milk', 'koyulaştırılmış süt'],
      defaultCategory: 'dairy',
      defaultShelfLifeDays: 365,
    },
    {
      canonicalName: 'buttermilk',
      canonicalNameTR: 'ayran',
      aliases: ['cultured buttermilk'],
      defaultCategory: 'dairy',
      defaultShelfLifeDays: 14,
    },
    {
      canonicalName: 'ghee',
      canonicalNameTR: 'sade yağ',
      aliases: ['clarified butter', 'tereyağı'],
      defaultCategory: 'dairy',
      defaultShelfLifeDays: 90,
    },
    {
      canonicalName: 'heavy cream',
      canonicalNameTR: 'ağır krema',
      aliases: ['double cream', 'krem şanti'],
      defaultCategory: 'dairy',
      defaultShelfLifeDays: 7,
    },
    {
      canonicalName: 'goat cheese',
      canonicalNameTR: 'keçi peyniri',
      aliases: ['chevre', 'keçi peyniri'],
      defaultCategory: 'dairy',
      defaultShelfLifeDays: 14,
    },

    // PRODUCE (~40 entries)
    {
      canonicalName: 'tomatoes',
      canonicalNameTR: 'domates',
      aliases: ['tomato', 'cherry tomatoes', 'roma tomatoes', 'domates'],
      defaultCategory: 'produce',
      defaultShelfLifeDays: 7,
    },
    {
      canonicalName: 'onions',
      canonicalNameTR: 'soğan',
      aliases: ['onion', 'yellow onions', 'red onions', 'white onions', 'soğanlar'],
      defaultCategory: 'produce',
      defaultShelfLifeDays: 30,
    },
    {
      canonicalName: 'garlic',
      canonicalNameTR: 'sarımsak',
      aliases: ['garlic cloves', 'sarımsak dişi'],
      defaultCategory: 'produce',
      defaultShelfLifeDays: 60,
    },
    {
      canonicalName: 'potatoes',
      canonicalNameTR: 'patates',
      aliases: ['potato', 'russet potatoes', 'yukon gold', 'patatesi'],
      defaultCategory: 'produce',
      defaultShelfLifeDays: 30,
    },
    {
      canonicalName: 'carrots',
      canonicalNameTR: 'havuç',
      aliases: ['carrot', 'baby carrots', 'havuçlar'],
      defaultCategory: 'produce',
      defaultShelfLifeDays: 14,
    },
    {
      canonicalName: 'bell peppers',
      canonicalNameTR: 'biber',
      aliases: ['bell pepper', 'red pepper', 'green pepper', 'dolma biberı'],
      defaultCategory: 'produce',
      defaultShelfLifeDays: 10,
    },
    {
      canonicalName: 'cucumber',
      canonicalNameTR: 'salatalık',
      aliases: ['cucumbers', 'salatalıklar'],
      defaultCategory: 'produce',
      defaultShelfLifeDays: 7,
    },
    {
      canonicalName: 'lettuce',
      canonicalNameTR: 'marul',
      aliases: ['romaine', 'iceberg lettuce', 'green leaf', 'kıvırcık marul'],
      defaultCategory: 'produce',
      defaultShelfLifeDays: 7,
    },
    {
      canonicalName: 'spinach',
      canonicalNameTR: 'ıspanak',
      aliases: ['baby spinach', 'fresh spinach', 'ıspanak yaprakları'],
      defaultCategory: 'produce',
      defaultShelfLifeDays: 5,
    },
    {
      canonicalName: 'broccoli',
      canonicalNameTR: 'brokoli',
      aliases: ['broccoli florets', 'brokoliler'],
      defaultCategory: 'produce',
      defaultShelfLifeDays: 7,
    },
    {
      canonicalName: 'mushrooms',
      canonicalNameTR: 'mantar',
      aliases: ['button mushrooms', 'cremini', 'portobello', 'mantarlar'],
      defaultCategory: 'produce',
      defaultShelfLifeDays: 7,
    },
    {
      canonicalName: 'zucchini',
      canonicalNameTR: 'kabak',
      aliases: ['courgette', 'sakız kabağı'],
      defaultCategory: 'produce',
      defaultShelfLifeDays: 10,
    },
    {
      canonicalName: 'eggplant',
      canonicalNameTR: 'patlıcan',
      aliases: ['aubergine', 'patlıcanlar'],
      defaultCategory: 'produce',
      defaultShelfLifeDays: 10,
    },
    {
      canonicalName: 'corn',
      canonicalNameTR: 'mısır',
      aliases: ['sweet corn', 'corn on the cob', 'tatlı mısır'],
      defaultCategory: 'produce',
      defaultShelfLifeDays: 5,
    },
    {
      canonicalName: 'peas',
      canonicalNameTR: 'bezelye',
      aliases: ['green peas', 'fresh peas', 'taze bezelye'],
      defaultCategory: 'produce',
      defaultShelfLifeDays: 7,
    },
    {
      canonicalName: 'green beans',
      canonicalNameTR: 'taze fasulye',
      aliases: ['string beans', 'snap beans', 'çalı fasulyesi'],
      defaultCategory: 'produce',
      defaultShelfLifeDays: 7,
    },
    {
      canonicalName: 'celery',
      canonicalNameTR: 'kereviz',
      aliases: ['celery stalks', 'kereviz sapı'],
      defaultCategory: 'produce',
      defaultShelfLifeDays: 14,
    },
    {
      canonicalName: 'avocado',
      canonicalNameTR: 'avokado',
      aliases: ['avocados', 'hass avocado', 'avokadolar'],
      defaultCategory: 'produce',
      defaultShelfLifeDays: 5,
    },
    {
      canonicalName: 'lemon',
      canonicalNameTR: 'limon',
      aliases: ['lemons', 'fresh lemon', 'limonlar'],
      defaultCategory: 'produce',
      defaultShelfLifeDays: 14,
    },
    {
      canonicalName: 'lime',
      canonicalNameTR: 'misket limonu',
      aliases: ['limes', 'key lime', 'misket limonları'],
      defaultCategory: 'produce',
      defaultShelfLifeDays: 14,
    },
    {
      canonicalName: 'oranges',
      canonicalNameTR: 'portakal',
      aliases: ['orange', 'navel oranges', 'blood orange', 'portalaklar'],
      defaultCategory: 'produce',
      defaultShelfLifeDays: 14,
    },
    {
      canonicalName: 'apples',
      canonicalNameTR: 'elma',
      aliases: ['apple', 'granny smith', 'honeycrisp', 'elmalar'],
      defaultCategory: 'produce',
      defaultShelfLifeDays: 30,
    },
    {
      canonicalName: 'bananas',
      canonicalNameTR: 'muz',
      aliases: ['banana', 'muzlar'],
      defaultCategory: 'produce',
      defaultShelfLifeDays: 5,
    },
    {
      canonicalName: 'strawberries',
      canonicalNameTR: 'çilek',
      aliases: ['strawberry', 'fresh strawberries', 'çilekler'],
      defaultCategory: 'produce',
      defaultShelfLifeDays: 5,
    },
    {
      canonicalName: 'blueberries',
      canonicalNameTR: 'yaban mersini',
      aliases: ['blueberry', 'fresh blueberries', 'maviyemiş'],
      defaultCategory: 'produce',
      defaultShelfLifeDays: 7,
    },
    {
      canonicalName: 'grapes',
      canonicalNameTR: 'üzüm',
      aliases: ['green grapes', 'red grapes', 'üzümler'],
      defaultCategory: 'produce',
      defaultShelfLifeDays: 7,
    },
    {
      canonicalName: 'watermelon',
      canonicalNameTR: 'karpuz',
      aliases: ['seedless watermelon', 'karpuzlar'],
      defaultCategory: 'produce',
      defaultShelfLifeDays: 14,
    },
    {
      canonicalName: 'melon',
      canonicalNameTR: 'kavun',
      aliases: ['cantaloupe', 'honeydew', 'kavunlar'],
      defaultCategory: 'produce',
      defaultShelfLifeDays: 7,
    },
    {
      canonicalName: 'pineapple',
      canonicalNameTR: 'ananas',
      aliases: ['fresh pineapple', 'ananaslar'],
      defaultCategory: 'produce',
      defaultShelfLifeDays: 5,
    },
    {
      canonicalName: 'mango',
      canonicalNameTR: 'mango',
      aliases: ['mangoes', 'fresh mango', 'mangolar'],
      defaultCategory: 'produce',
      defaultShelfLifeDays: 7,
    },
    {
      canonicalName: 'ginger',
      canonicalNameTR: 'zencefil',
      aliases: ['fresh ginger', 'ginger root', 'zencefil kökü'],
      defaultCategory: 'produce',
      defaultShelfLifeDays: 21,
    },
    {
      canonicalName: 'parsley',
      canonicalNameTR: 'maydanoz',
      aliases: ['fresh parsley', 'flat leaf parsley', 'taze maydanoz'],
      defaultCategory: 'produce',
      defaultShelfLifeDays: 7,
    },
    {
      canonicalName: 'cilantro',
      canonicalNameTR: 'kişniş',
      aliases: ['coriander leaves', 'fresh cilantro', 'kişniş yaprağı'],
      defaultCategory: 'produce',
      defaultShelfLifeDays: 7,
    },
    {
      canonicalName: 'mint',
      canonicalNameTR: 'nane',
      aliases: ['fresh mint', 'spearmint', 'taze nane'],
      defaultCategory: 'produce',
      defaultShelfLifeDays: 7,
    },
    {
      canonicalName: 'dill',
      canonicalNameTR: 'dereotu',
      aliases: ['fresh dill', 'dill weed', 'taze dereotu'],
      defaultCategory: 'produce',
      defaultShelfLifeDays: 7,
    },
    {
      canonicalName: 'basil',
      canonicalNameTR: 'fesleğen',
      aliases: ['fresh basil', 'sweet basil', 'taze fesleğen'],
      defaultCategory: 'produce',
      defaultShelfLifeDays: 5,
    },
    {
      canonicalName: 'rosemary',
      canonicalNameTR: 'biberiye',
      aliases: ['fresh rosemary', 'taze biberiye'],
      defaultCategory: 'produce',
      defaultShelfLifeDays: 14,
    },
    {
      canonicalName: 'thyme',
      canonicalNameTR: 'kekik',
      aliases: ['fresh thyme', 'taze kekik'],
      defaultCategory: 'produce',
      defaultShelfLifeDays: 14,
    },
    {
      canonicalName: 'chives',
      canonicalNameTR: 'frenk soğanı',
      aliases: ['fresh chives', 'taze frenk soğanı'],
      defaultCategory: 'produce',
      defaultShelfLifeDays: 7,
    },
    {
      canonicalName: 'scallions',
      canonicalNameTR: 'yeşil soğan',
      aliases: ['green onions', 'spring onions', 'taze soğan'],
      defaultCategory: 'produce',
      defaultShelfLifeDays: 7,
    },

    // MEAT (~15 entries)
    {
      canonicalName: 'chicken breast',
      canonicalNameTR: 'tavuk göğsü',
      aliases: ['chicken breasts', 'boneless chicken breast', 'tavuk fileto'],
      defaultCategory: 'meat',
      defaultShelfLifeDays: 2,
    },
    {
      canonicalName: 'chicken thighs',
      canonicalNameTR: 'tavuk butu',
      aliases: ['chicken thigh', 'boneless chicken thighs', 'tavuk uyluk'],
      defaultCategory: 'meat',
      defaultShelfLifeDays: 2,
    },
    {
      canonicalName: 'ground beef',
      canonicalNameTR: 'kıyma',
      aliases: ['beef mince', 'minced beef', 'dana kıyma'],
      defaultCategory: 'meat',
      defaultShelfLifeDays: 2,
    },
    {
      canonicalName: 'beef steak',
      canonicalNameTR: 'biftek',
      aliases: ['ribeye', 'sirloin', 'strip steak', 'dana biftek'],
      defaultCategory: 'meat',
      defaultShelfLifeDays: 3,
    },
    {
      canonicalName: 'lamb',
      canonicalNameTR: 'kuzu',
      aliases: ['lamb chops', 'lamb shoulder', 'kuzu eti'],
      defaultCategory: 'meat',
      defaultShelfLifeDays: 3,
    },
    {
      canonicalName: 'pork chop',
      canonicalNameTR: 'domuz pirzolası',
      aliases: ['pork chops', 'bone-in pork chops'],
      defaultCategory: 'meat',
      defaultShelfLifeDays: 3,
    },
    {
      canonicalName: 'bacon',
      canonicalNameTR: 'pastırma',
      aliases: ['turkey bacon', 'pork bacon', 'bacon strips'],
      defaultCategory: 'meat',
      defaultShelfLifeDays: 7,
    },
    {
      canonicalName: 'sausage',
      canonicalNameTR: 'sosis',
      aliases: ['italian sausage', 'breakfast sausage', 'sucuk'],
      defaultCategory: 'meat',
      defaultShelfLifeDays: 5,
    },
    {
      canonicalName: 'turkey',
      canonicalNameTR: 'hindi',
      aliases: ['turkey breast', 'ground turkey', 'hindi göğsü'],
      defaultCategory: 'meat',
      defaultShelfLifeDays: 2,
    },
    {
      canonicalName: 'ham',
      canonicalNameTR: 'jambon',
      aliases: ['deli ham', 'smoked ham', 'jambonlar'],
      defaultCategory: 'meat',
      defaultShelfLifeDays: 7,
    },
    {
      canonicalName: 'salami',
      canonicalNameTR: 'salam',
      aliases: ['genoa salami', 'hard salami', 'salamlar'],
      defaultCategory: 'meat',
      defaultShelfLifeDays: 21,
    },
    {
      canonicalName: 'ground turkey',
      canonicalNameTR: 'hindi kıyma',
      aliases: ['turkey mince', 'minced turkey'],
      defaultCategory: 'meat',
      defaultShelfLifeDays: 2,
    },
    {
      canonicalName: 'veal',
      canonicalNameTR: 'dana eti',
      aliases: ['veal cutlet', 'veal scaloppine', 'dana bonfile'],
      defaultCategory: 'meat',
      defaultShelfLifeDays: 3,
    },
    {
      canonicalName: 'liver',
      canonicalNameTR: 'ciğer',
      aliases: ['chicken liver', 'beef liver', 'tavuk ciğeri'],
      defaultCategory: 'meat',
      defaultShelfLifeDays: 2,
    },
    {
      canonicalName: 'meatballs',
      canonicalNameTR: 'köfte',
      aliases: ['beef meatballs', 'turkish meatballs', 'izgara köfte'],
      defaultCategory: 'meat',
      defaultShelfLifeDays: 2,
    },

    // SEAFOOD (~10 entries)
    {
      canonicalName: 'salmon',
      canonicalNameTR: 'somon',
      aliases: ['salmon fillet', 'atlantic salmon', 'somon fileto'],
      defaultCategory: 'seafood',
      defaultShelfLifeDays: 2,
    },
    {
      canonicalName: 'shrimp',
      canonicalNameTR: 'karides',
      aliases: ['prawns', 'jumbo shrimp', 'karides kuyrukları'],
      defaultCategory: 'seafood',
      defaultShelfLifeDays: 2,
    },
    {
      canonicalName: 'tuna',
      canonicalNameTR: 'ton balığı',
      aliases: ['tuna steak', 'yellowfin tuna', 'ton balığı konservesi'],
      defaultCategory: 'seafood',
      defaultShelfLifeDays: 2,
    },
    {
      canonicalName: 'cod',
      canonicalNameTR: 'morina',
      aliases: ['cod fillet', 'atlantic cod', 'morina balığı'],
      defaultCategory: 'seafood',
      defaultShelfLifeDays: 2,
    },
    {
      canonicalName: 'sea bass',
      canonicalNameTR: 'levrek',
      aliases: ['branzino', 'european sea bass', 'levrek balığı'],
      defaultCategory: 'seafood',
      defaultShelfLifeDays: 2,
    },
    {
      canonicalName: 'mussels',
      canonicalNameTR: 'midye',
      aliases: ['fresh mussels', 'blue mussels', 'midyeler'],
      defaultCategory: 'seafood',
      defaultShelfLifeDays: 1,
    },
    {
      canonicalName: 'squid',
      canonicalNameTR: 'kalamar',
      aliases: ['calamari', 'fresh squid', 'kalamar halkaları'],
      defaultCategory: 'seafood',
      defaultShelfLifeDays: 2,
    },
    {
      canonicalName: 'anchovies',
      canonicalNameTR: 'hamsi',
      aliases: ['fresh anchovies', 'anchovy fillets', 'taze hamsi'],
      defaultCategory: 'seafood',
      defaultShelfLifeDays: 1,
    },
    {
      canonicalName: 'mackerel',
      canonicalNameTR: 'uskumru',
      aliases: ['spanish mackerel', 'atlantic mackerel', 'taze uskumru'],
      defaultCategory: 'seafood',
      defaultShelfLifeDays: 2,
    },
    {
      canonicalName: 'trout',
      canonicalNameTR: 'alabalık',
      aliases: ['rainbow trout', 'trout fillet', 'alabalık fileto'],
      defaultCategory: 'seafood',
      defaultShelfLifeDays: 2,
    },

    // GRAINS (~20 entries)
    {
      canonicalName: 'rice',
      canonicalNameTR: 'pirinç',
      aliases: ['white rice', 'basmati rice', 'jasmine rice', 'beyaz pirinç'],
      defaultCategory: 'grains',
      defaultShelfLifeDays: 365,
    },
    {
      canonicalName: 'pasta',
      canonicalNameTR: 'makarna',
      aliases: ['spaghetti', 'penne', 'fettuccine', 'spagetti'],
      defaultCategory: 'grains',
      defaultShelfLifeDays: 365,
    },
    {
      canonicalName: 'bread',
      canonicalNameTR: 'ekmek',
      aliases: ['loaf bread', 'white bread', 'whole wheat bread', 'tam buğday ekmeği'],
      defaultCategory: 'grains',
      defaultShelfLifeDays: 5,
    },
    {
      canonicalName: 'flour',
      canonicalNameTR: 'un',
      aliases: ['all-purpose flour', 'bread flour', 'cake flour', 'buğday unu'],
      defaultCategory: 'grains',
      defaultShelfLifeDays: 365,
    },
    {
      canonicalName: 'oats',
      canonicalNameTR: 'yulaf',
      aliases: ['rolled oats', 'old fashioned oats', 'quick oats', 'yulaf ezmesi'],
      defaultCategory: 'grains',
      defaultShelfLifeDays: 365,
    },
    {
      canonicalName: 'quinoa',
      canonicalNameTR: 'kinoa',
      aliases: ['white quinoa', 'red quinoa', 'tricolor quinoa'],
      defaultCategory: 'grains',
      defaultShelfLifeDays: 365,
    },
    {
      canonicalName: 'couscous',
      canonicalNameTR: 'kuskus',
      aliases: ['moroccan couscous', 'israeli couscous'],
      defaultCategory: 'grains',
      defaultShelfLifeDays: 365,
    },
    {
      canonicalName: 'bulgur',
      canonicalNameTR: 'bulgur',
      aliases: ['fine bulgur', 'coarse bulgur', 'köftelik bulgur'],
      defaultCategory: 'grains',
      defaultShelfLifeDays: 365,
    },
    {
      canonicalName: 'noodles',
      canonicalNameTR: 'erişte',
      aliases: ['egg noodles', 'rice noodles', 'udon noodles', 'şehriye'],
      defaultCategory: 'grains',
      defaultShelfLifeDays: 365,
    },
    {
      canonicalName: 'tortillas',
      canonicalNameTR: 'tortilla',
      aliases: ['flour tortillas', 'corn tortillas', 'wrap'],
      defaultCategory: 'grains',
      defaultShelfLifeDays: 14,
    },
    {
      canonicalName: 'pita',
      canonicalNameTR: 'pide',
      aliases: ['pita bread', 'pide ekmeği'],
      defaultCategory: 'grains',
      defaultShelfLifeDays: 7,
    },
    {
      canonicalName: 'cornmeal',
      canonicalNameTR: 'mısır unu',
      aliases: ['polenta', 'corn flour', 'mısır irmiği'],
      defaultCategory: 'grains',
      defaultShelfLifeDays: 365,
    },
    {
      canonicalName: 'semolina',
      canonicalNameTR: 'irmik',
      aliases: ['semolina flour', 'ince irmik'],
      defaultCategory: 'grains',
      defaultShelfLifeDays: 365,
    },
    {
      canonicalName: 'barley',
      canonicalNameTR: 'arpa',
      aliases: ['pearl barley', 'hulled barley', 'arpa taneleri'],
      defaultCategory: 'grains',
      defaultShelfLifeDays: 365,
    },
    {
      canonicalName: 'rye',
      canonicalNameTR: 'çavdar',
      aliases: ['rye flour', 'rye bread', 'çavdar unu'],
      defaultCategory: 'grains',
      defaultShelfLifeDays: 365,
    },
    {
      canonicalName: 'breadcrumbs',
      canonicalNameTR: 'galeta unu',
      aliases: ['panko', 'italian breadcrumbs', 'ekmek kırıntısı'],
      defaultCategory: 'grains',
      defaultShelfLifeDays: 180,
    },
    {
      canonicalName: 'crackers',
      canonicalNameTR: 'tuzlu kraker',
      aliases: ['saltine crackers', 'water crackers', 'krakerler'],
      defaultCategory: 'grains',
      defaultShelfLifeDays: 180,
    },
    {
      canonicalName: 'cereal',
      canonicalNameTR: 'tahıl gevreği',
      aliases: ['breakfast cereal', 'corn flakes', 'mısır gevreği'],
      defaultCategory: 'grains',
      defaultShelfLifeDays: 180,
    },
    {
      canonicalName: 'granola',
      canonicalNameTR: 'granola',
      aliases: ['granola clusters', 'granola cereal'],
      defaultCategory: 'grains',
      defaultShelfLifeDays: 180,
    },
    {
      canonicalName: 'pizza dough',
      canonicalNameTR: 'pizza hamuru',
      aliases: ['fresh pizza dough', 'pizza hamurunuz'],
      defaultCategory: 'grains',
      defaultShelfLifeDays: 7,
    },

    // BAKING (~15 entries)
    {
      canonicalName: 'sugar',
      canonicalNameTR: 'şeker',
      aliases: ['white sugar', 'granulated sugar', 'toz şeker'],
      defaultCategory: 'baking',
      defaultShelfLifeDays: 730,
    },
    {
      canonicalName: 'brown sugar',
      canonicalNameTR: 'esmer şeker',
      aliases: ['light brown sugar', 'dark brown sugar'],
      defaultCategory: 'baking',
      defaultShelfLifeDays: 730,
    },
    {
      canonicalName: 'powdered sugar',
      canonicalNameTR: 'pudra şekeri',
      aliases: ['icing sugar', 'confectioners sugar'],
      defaultCategory: 'baking',
      defaultShelfLifeDays: 730,
    },
    {
      canonicalName: 'baking powder',
      canonicalNameTR: 'kabartma tozu',
      aliases: ['double acting baking powder'],
      defaultCategory: 'baking',
      defaultShelfLifeDays: 365,
    },
    {
      canonicalName: 'baking soda',
      canonicalNameTR: 'karbonat',
      aliases: ['sodium bicarbonate', 'bicarbonate of soda'],
      defaultCategory: 'baking',
      defaultShelfLifeDays: 730,
    },
    {
      canonicalName: 'vanilla extract',
      canonicalNameTR: 'vanilya özütü',
      aliases: ['pure vanilla', 'vanilya aroması'],
      defaultCategory: 'baking',
      defaultShelfLifeDays: 1825,
    },
    {
      canonicalName: 'cocoa powder',
      canonicalNameTR: 'kakao',
      aliases: ['unsweetened cocoa', 'dutch cocoa', 'kakao tozu'],
      defaultCategory: 'baking',
      defaultShelfLifeDays: 730,
    },
    {
      canonicalName: 'chocolate',
      canonicalNameTR: 'çikolata',
      aliases: ['dark chocolate', 'milk chocolate', 'bitter çikolata'],
      defaultCategory: 'baking',
      defaultShelfLifeDays: 365,
    },
    {
      canonicalName: 'honey',
      canonicalNameTR: 'bal',
      aliases: ['raw honey', 'organic honey', 'çiçek balı'],
      defaultCategory: 'baking',
      defaultShelfLifeDays: 1825,
    },
    {
      canonicalName: 'maple syrup',
      canonicalNameTR: 'akça ağaç şurubu',
      aliases: ['pure maple syrup', 'grade a maple syrup'],
      defaultCategory: 'baking',
      defaultShelfLifeDays: 365,
    },
    {
      canonicalName: 'molasses',
      canonicalNameTR: 'pekmez',
      aliases: ['blackstrap molasses', 'üzüm pekmezi'],
      defaultCategory: 'baking',
      defaultShelfLifeDays: 730,
    },
    {
      canonicalName: 'cornstarch',
      canonicalNameTR: 'nişasta',
      aliases: ['corn flour', 'mısır nişastası'],
      defaultCategory: 'baking',
      defaultShelfLifeDays: 730,
    },
    {
      canonicalName: 'yeast',
      canonicalNameTR: 'maya',
      aliases: ['active dry yeast', 'instant yeast', 'kuru maya'],
      defaultCategory: 'baking',
      defaultShelfLifeDays: 365,
    },
    {
      canonicalName: 'gelatin',
      canonicalNameTR: 'jelatin',
      aliases: ['unflavored gelatin', 'gelatin powder'],
      defaultCategory: 'baking',
      defaultShelfLifeDays: 730,
    },
    {
      canonicalName: 'food coloring',
      canonicalNameTR: 'gıda boyası',
      aliases: ['gel food coloring', 'liquid food color'],
      defaultCategory: 'baking',
      defaultShelfLifeDays: 730,
    },

    // SPICES (~25 entries)
    {
      canonicalName: 'salt',
      canonicalNameTR: 'tuz',
      aliases: ['sea salt', 'kosher salt', 'table salt', 'deniz tuzu'],
      defaultCategory: 'spices',
      defaultShelfLifeDays: 1825,
    },
    {
      canonicalName: 'black pepper',
      canonicalNameTR: 'karabiber',
      aliases: ['ground black pepper', 'peppercorns', 'karabiber taneleri'],
      defaultCategory: 'spices',
      defaultShelfLifeDays: 730,
    },
    {
      canonicalName: 'red pepper flakes',
      canonicalNameTR: 'pul biber',
      aliases: ['crushed red pepper', 'red chili flakes', 'aleppo pepper'],
      defaultCategory: 'spices',
      defaultShelfLifeDays: 730,
    },
    {
      canonicalName: 'cumin',
      canonicalNameTR: 'kimyon',
      aliases: ['ground cumin', 'cumin seeds', 'kimyon tohumu'],
      defaultCategory: 'spices',
      defaultShelfLifeDays: 730,
    },
    {
      canonicalName: 'paprika',
      canonicalNameTR: 'tatlı toz biber',
      aliases: ['sweet paprika', 'smoked paprika', 'közlenmiş biber tozu'],
      defaultCategory: 'spices',
      defaultShelfLifeDays: 730,
    },
    {
      canonicalName: 'turmeric',
      canonicalNameTR: 'zerdeçal',
      aliases: ['ground turmeric', 'turmeric powder', 'hint safranı'],
      defaultCategory: 'spices',
      defaultShelfLifeDays: 730,
    },
    {
      canonicalName: 'cinnamon',
      canonicalNameTR: 'tarçın',
      aliases: ['ground cinnamon', 'cinnamon sticks', 'tarçın çubuğu'],
      defaultCategory: 'spices',
      defaultShelfLifeDays: 730,
    },
    {
      canonicalName: 'oregano',
      canonicalNameTR: 'kekik',
      aliases: ['dried oregano', 'greek oregano', 'kurutulmuş kekik'],
      defaultCategory: 'spices',
      defaultShelfLifeDays: 730,
    },
    {
      canonicalName: 'bay leaf',
      canonicalNameTR: 'defne yaprağı',
      aliases: ['bay leaves', 'dried bay leaves', 'defne yaprakları'],
      defaultCategory: 'spices',
      defaultShelfLifeDays: 730,
    },
    {
      canonicalName: 'nutmeg',
      canonicalNameTR: 'muskat',
      aliases: ['ground nutmeg', 'whole nutmeg', 'hindistan cevizi'],
      defaultCategory: 'spices',
      defaultShelfLifeDays: 730,
    },
    {
      canonicalName: 'cloves',
      canonicalNameTR: 'karanfil',
      aliases: ['whole cloves', 'ground cloves', 'karanfil taneleri'],
      defaultCategory: 'spices',
      defaultShelfLifeDays: 730,
    },
    {
      canonicalName: 'cardamom',
      canonicalNameTR: 'kakule',
      aliases: ['green cardamom', 'cardamom pods', 'kakule taneleri'],
      defaultCategory: 'spices',
      defaultShelfLifeDays: 730,
    },
    {
      canonicalName: 'coriander',
      canonicalNameTR: 'kişniş',
      aliases: ['ground coriander', 'coriander seeds', 'kişniş tohumu'],
      defaultCategory: 'spices',
      defaultShelfLifeDays: 730,
    },
    {
      canonicalName: 'chili powder',
      canonicalNameTR: 'acı biber tozu',
      aliases: ['red chili powder', 'cayenne pepper', 'kırmızı biber tozu'],
      defaultCategory: 'spices',
      defaultShelfLifeDays: 730,
    },
    {
      canonicalName: 'cayenne',
      canonicalNameTR: 'kırmızı biber',
      aliases: ['cayenne pepper', 'ground cayenne'],
      defaultCategory: 'spices',
      defaultShelfLifeDays: 730,
    },
    {
      canonicalName: 'sumac',
      canonicalNameTR: 'sumak',
      aliases: ['ground sumac', 'sumac powder', 'sumak tozu'],
      defaultCategory: 'spices',
      defaultShelfLifeDays: 730,
    },
    {
      canonicalName: 'allspice',
      canonicalNameTR: 'yeni bahar',
      aliases: ['ground allspice', 'whole allspice'],
      defaultCategory: 'spices',
      defaultShelfLifeDays: 730,
    },
    {
      canonicalName: 'saffron',
      canonicalNameTR: 'safran',
      aliases: ['saffron threads', 'spanish saffron', 'safran iplikleri'],
      defaultCategory: 'spices',
      defaultShelfLifeDays: 1825,
    },
    {
      canonicalName: 'fennel seeds',
      canonicalNameTR: 'rezene',
      aliases: ['fennel', 'fennel seed', 'rezene tohumu'],
      defaultCategory: 'spices',
      defaultShelfLifeDays: 730,
    },
    {
      canonicalName: 'star anise',
      canonicalNameTR: 'yıldız anason',
      aliases: ['whole star anise', 'anise star'],
      defaultCategory: 'spices',
      defaultShelfLifeDays: 730,
    },
    {
      canonicalName: 'white pepper',
      canonicalNameTR: 'beyaz biber',
      aliases: ['ground white pepper', 'white peppercorns'],
      defaultCategory: 'spices',
      defaultShelfLifeDays: 730,
    },
    {
      canonicalName: 'curry powder',
      canonicalNameTR: 'köri',
      aliases: ['mild curry powder', 'hot curry powder', 'köri tozu'],
      defaultCategory: 'spices',
      defaultShelfLifeDays: 730,
    },
    {
      canonicalName: 'mustard seeds',
      canonicalNameTR: 'hardal tohumu',
      aliases: ['yellow mustard seeds', 'black mustard seeds'],
      defaultCategory: 'spices',
      defaultShelfLifeDays: 730,
    },
    {
      canonicalName: 'za\'atar',
      canonicalNameTR: 'zahter',
      aliases: ['zaatar', 'middle eastern spice blend'],
      defaultCategory: 'spices',
      defaultShelfLifeDays: 730,
    },
    {
      canonicalName: 'harissa',
      canonicalNameTR: 'harissa',
      aliases: ['harissa paste', 'north african spice paste'],
      defaultCategory: 'spices',
      defaultShelfLifeDays: 90,
    },

    // BEVERAGES (~10 entries)
    {
      canonicalName: 'water',
      canonicalNameTR: 'su',
      aliases: ['bottled water', 'mineral water', 'maden suyu'],
      defaultCategory: 'beverages',
      defaultShelfLifeDays: 365,
    },
    {
      canonicalName: 'coffee',
      canonicalNameTR: 'kahve',
      aliases: ['ground coffee', 'coffee beans', 'kahve çekirdekleri'],
      defaultCategory: 'beverages',
      defaultShelfLifeDays: 180,
    },
    {
      canonicalName: 'tea',
      canonicalNameTR: 'çay',
      aliases: ['black tea', 'green tea', 'siyah çay', 'yeşil çay'],
      defaultCategory: 'beverages',
      defaultShelfLifeDays: 730,
    },
    {
      canonicalName: 'orange juice',
      canonicalNameTR: 'portakal suyu',
      aliases: ['fresh orange juice', 'oj', 'taze portakal suyu'],
      defaultCategory: 'beverages',
      defaultShelfLifeDays: 7,
    },
    {
      canonicalName: 'apple juice',
      canonicalNameTR: 'elma suyu',
      aliases: ['fresh apple juice', 'taze elma suyu'],
      defaultCategory: 'beverages',
      defaultShelfLifeDays: 7,
    },
    {
      canonicalName: 'coconut milk',
      canonicalNameTR: 'hindistan cevizi sütü',
      aliases: ['canned coconut milk', 'coconut cream'],
      defaultCategory: 'beverages',
      defaultShelfLifeDays: 365,
    },
    {
      canonicalName: 'almond milk',
      canonicalNameTR: 'badem sütü',
      aliases: ['unsweetened almond milk', 'vanilla almond milk'],
      defaultCategory: 'beverages',
      defaultShelfLifeDays: 7,
    },
    {
      canonicalName: 'beer',
      canonicalNameTR: 'bira',
      aliases: ['lager', 'ale', 'craft beer', 'biralar'],
      defaultCategory: 'beverages',
      defaultShelfLifeDays: 180,
    },
    {
      canonicalName: 'wine',
      canonicalNameTR: 'şarap',
      aliases: ['red wine', 'white wine', 'kırmızı şarap', 'beyaz şarap'],
      defaultCategory: 'beverages',
      defaultShelfLifeDays: 1825,
    },
    {
      canonicalName: 'lemonade',
      canonicalNameTR: 'limonata',
      aliases: ['fresh lemonade', 'homemade lemonade'],
      defaultCategory: 'beverages',
      defaultShelfLifeDays: 5,
    },

    // SNACKS (~10 entries)
    {
      canonicalName: 'chips',
      canonicalNameTR: 'cips',
      aliases: ['potato chips', 'tortilla chips', 'patates cipsi'],
      defaultCategory: 'snacks',
      defaultShelfLifeDays: 180,
    },
    {
      canonicalName: 'nuts',
      canonicalNameTR: 'kuruyemiş',
      aliases: ['mixed nuts', 'roasted nuts', 'karışık kuruyemiş'],
      defaultCategory: 'snacks',
      defaultShelfLifeDays: 180,
    },
    {
      canonicalName: 'almonds',
      canonicalNameTR: 'badem',
      aliases: ['raw almonds', 'roasted almonds', 'bademler'],
      defaultCategory: 'snacks',
      defaultShelfLifeDays: 180,
    },
    {
      canonicalName: 'walnuts',
      canonicalNameTR: 'ceviz',
      aliases: ['walnut halves', 'cevizler'],
      defaultCategory: 'snacks',
      defaultShelfLifeDays: 180,
    },
    {
      canonicalName: 'peanuts',
      canonicalNameTR: 'yer fıstığı',
      aliases: ['roasted peanuts', 'salted peanuts', 'yer fıstıkları'],
      defaultCategory: 'snacks',
      defaultShelfLifeDays: 180,
    },
    {
      canonicalName: 'pistachios',
      canonicalNameTR: 'antep fıstığı',
      aliases: ['roasted pistachios', 'shelled pistachios', 'kabuklu fıstık'],
      defaultCategory: 'snacks',
      defaultShelfLifeDays: 180,
    },
    {
      canonicalName: 'hazelnuts',
      canonicalNameTR: 'fındık',
      aliases: ['roasted hazelnuts', 'fındıklar'],
      defaultCategory: 'snacks',
      defaultShelfLifeDays: 180,
    },
    {
      canonicalName: 'dried fruits',
      canonicalNameTR: 'kuru meyve',
      aliases: ['dried apricots', 'raisins', 'kuru kayısı', 'kuru üzüm'],
      defaultCategory: 'snacks',
      defaultShelfLifeDays: 180,
    },
    {
      canonicalName: 'popcorn',
      canonicalNameTR: 'mısır patlaği',
      aliases: ['microwave popcorn', 'popping corn', 'patlamış mısır'],
      defaultCategory: 'snacks',
      defaultShelfLifeDays: 180,
    },
    {
      canonicalName: 'trail mix',
      canonicalNameTR: 'karışık atıştırmalık',
      aliases: ['mixed snacks', 'nut and seed mix'],
      defaultCategory: 'snacks',
      defaultShelfLifeDays: 180,
    },

    // CONDIMENTS (~20 entries)
    {
      canonicalName: 'olive oil',
      canonicalNameTR: 'zeytinyağı',
      aliases: ['extra virgin olive oil', 'evoo', 'sızma zeytinyağı'],
      defaultCategory: 'condiments',
      defaultShelfLifeDays: 730,
    },
    {
      canonicalName: 'vegetable oil',
      canonicalNameTR: 'sıvı yağ',
      aliases: ['canola oil', 'sunflower oil', 'ayçiçek yağı'],
      defaultCategory: 'condiments',
      defaultShelfLifeDays: 730,
    },
    {
      canonicalName: 'soy sauce',
      canonicalNameTR: 'soya sosu',
      aliases: ['light soy sauce', 'dark soy sauce', 'tamari'],
      defaultCategory: 'condiments',
      defaultShelfLifeDays: 730,
    },
    {
      canonicalName: 'vinegar',
      canonicalNameTR: 'sirke',
      aliases: ['white vinegar', 'apple cider vinegar', 'elma sirkesi'],
      defaultCategory: 'condiments',
      defaultShelfLifeDays: 1825,
    },
    {
      canonicalName: 'ketchup',
      canonicalNameTR: 'ketçap',
      aliases: ['tomato ketchup', 'domates ketçabı'],
      defaultCategory: 'condiments',
      defaultShelfLifeDays: 365,
    },
    {
      canonicalName: 'mustard',
      canonicalNameTR: 'hardal',
      aliases: ['dijon mustard', 'yellow mustard', 'whole grain mustard'],
      defaultCategory: 'condiments',
      defaultShelfLifeDays: 365,
    },
    {
      canonicalName: 'mayonnaise',
      canonicalNameTR: 'mayanez',
      aliases: ['mayo', 'light mayo', 'hellmans'],
      defaultCategory: 'condiments',
      defaultShelfLifeDays: 60,
    },
    {
      canonicalName: 'hot sauce',
      canonicalNameTR: 'acı sos',
      aliases: ['tabasco', 'sriracha', 'hot pepper sauce'],
      defaultCategory: 'condiments',
      defaultShelfLifeDays: 365,
    },
    {
      canonicalName: 'worcestershire sauce',
      canonicalNameTR: 'worcestershire sos',
      aliases: ['worcestershire', 'lea & perrins'],
      defaultCategory: 'condiments',
      defaultShelfLifeDays: 730,
    },
    {
      canonicalName: 'tahini',
      canonicalNameTR: 'tahin',
      aliases: ['sesame paste', 'tahini paste', 'susam ezmesi'],
      defaultCategory: 'condiments',
      defaultShelfLifeDays: 180,
    },
    {
      canonicalName: 'tomato paste',
      canonicalNameTR: 'salça',
      aliases: ['tomato concentrate', 'domates salçası'],
      defaultCategory: 'condiments',
      defaultShelfLifeDays: 365,
    },
    {
      canonicalName: 'fish sauce',
      canonicalNameTR: 'balık sosu',
      aliases: ['nam pla', 'nuoc mam'],
      defaultCategory: 'condiments',
      defaultShelfLifeDays: 730,
    },
    {
      canonicalName: 'sesame oil',
      canonicalNameTR: 'susam yağı',
      aliases: ['toasted sesame oil', 'asian sesame oil'],
      defaultCategory: 'condiments',
      defaultShelfLifeDays: 365,
    },
    {
      canonicalName: 'coconut oil',
      canonicalNameTR: 'hindistan cevizi yağı',
      aliases: ['virgin coconut oil', 'organic coconut oil'],
      defaultCategory: 'condiments',
      defaultShelfLifeDays: 730,
    },
    {
      canonicalName: 'balsamic vinegar',
      canonicalNameTR: 'balzamik sirke',
      aliases: ['balsamic reduction', 'aged balsamic'],
      defaultCategory: 'condiments',
      defaultShelfLifeDays: 1825,
    },
    {
      canonicalName: 'rice vinegar',
      canonicalNameTR: 'pirinç sirkesi',
      aliases: ['rice wine vinegar', 'seasoned rice vinegar'],
      defaultCategory: 'condiments',
      defaultShelfLifeDays: 730,
    },
    {
      canonicalName: 'oyster sauce',
      canonicalNameTR: 'istiridye sosu',
      aliases: ['lee kum kee oyster sauce'],
      defaultCategory: 'condiments',
      defaultShelfLifeDays: 365,
    },
    {
      canonicalName: 'hoisin sauce',
      canonicalNameTR: 'hoisin sos',
      aliases: ['chinese bbq sauce', 'plum sauce'],
      defaultCategory: 'condiments',
      defaultShelfLifeDays: 365,
    },
    {
      canonicalName: 'sriracha',
      canonicalNameTR: 'sriracha',
      aliases: ['sriracha hot sauce', 'rooster sauce'],
      defaultCategory: 'condiments',
      defaultShelfLifeDays: 365,
    },
    {
      canonicalName: 'pomegranate molasses',
      canonicalNameTR: 'nar ekşisi',
      aliases: ['pomegranate syrup', 'nar pekmezi'],
      defaultCategory: 'condiments',
      defaultShelfLifeDays: 365,
    },
  ];

  // Use createMany with skipDuplicates for idempotent seeding
  const result = await prisma.ingredientCatalog.createMany({
    data: ingredients,
    skipDuplicates: true,
  });

  console.log(`✅ Seeded ${result.count} ingredient catalog entries`);

  // ── Seed Recipes ─────────────────────────────────────────────────────
  console.log('🍳 Seeding recipes...');

  const recipes = [
    // ── New York ──────────────────────────────────────────────────────
    {
      name: 'Classic New York Cheesecake',
      description: 'Rich and creamy cheesecake with a buttery graham cracker crust. A timeless NYC dessert.',
      prepTime: 30,
      cookTime: 60,
      servings: 12,
      calories: 410,
      protein: 7,
      carbs: 32,
      fat: 29,
      difficulty: 'INTERMEDIATE' as const,
      dietaryTags: ['vegetarian'],
      cuisineType: 'AMERICAN' as const,
      mealType: 'DESSERT' as const,
      imageStatus: 'COMPLETED' as const,
      scrapedFrom: 'curated',
      location: 'New York',
      latitude: 40.7128,
      longitude: -74.006,
      engagementLoves: 2840,
      engagementBookmarks: 1520,
      engagementViews: 18500,
      isViral: true,
      velocityScore: 92.5,
      ingredients: [
        { name: 'cream cheese', quantity: '900', unit: 'g', orderIndex: 0 },
        { name: 'sugar', quantity: '200', unit: 'g', orderIndex: 1 },
        { name: 'eggs', quantity: '4', unit: 'large', orderIndex: 2 },
        { name: 'sour cream', quantity: '240', unit: 'ml', orderIndex: 3 },
        { name: 'vanilla extract', quantity: '2', unit: 'tsp', orderIndex: 4 },
        { name: 'graham crackers', quantity: '200', unit: 'g', orderIndex: 5 },
        { name: 'butter', quantity: '75', unit: 'g', orderIndex: 6 },
      ],
      steps: [
        { orderIndex: 0, text: 'Preheat oven to 160°C (325°F). Crush graham crackers and mix with melted butter. Press into the bottom of a 9-inch springform pan.', duration: 600, techniqueTag: 'prep' },
        { orderIndex: 1, text: 'Beat cream cheese and sugar until smooth. Add eggs one at a time, mixing on low after each addition.', duration: 480, techniqueTag: 'mix' },
        { orderIndex: 2, text: 'Fold in sour cream and vanilla extract until just combined. Do not overmix.', duration: 120, techniqueTag: 'fold' },
        { orderIndex: 3, text: 'Pour filling over crust. Bake for 55-60 minutes until edges are set but center still jiggles slightly.', duration: 3600, techniqueTag: 'bake' },
        { orderIndex: 4, text: 'Turn off oven, crack the door, and let cheesecake cool inside for 1 hour. Refrigerate at least 4 hours before serving.', duration: 3600, techniqueTag: 'rest' },
      ],
    },
    {
      name: 'NYC Bacon Egg & Cheese on a Roll',
      description: 'The quintessential New York bodega breakfast sandwich. Crispy bacon, fluffy eggs, melted American cheese on a kaiser roll.',
      prepTime: 5,
      cookTime: 10,
      servings: 1,
      calories: 520,
      protein: 28,
      carbs: 35,
      fat: 30,
      difficulty: 'BEGINNER' as const,
      dietaryTags: [],
      cuisineType: 'AMERICAN' as const,
      mealType: 'BREAKFAST' as const,
      imageStatus: 'COMPLETED' as const,
      scrapedFrom: 'curated',
      location: 'New York',
      latitude: 40.7128,
      longitude: -74.006,
      engagementLoves: 3200,
      engagementBookmarks: 980,
      engagementViews: 22000,
      isViral: true,
      velocityScore: 95.0,
      ingredients: [
        { name: 'bacon', quantity: '3', unit: 'strips', orderIndex: 0 },
        { name: 'eggs', quantity: '2', unit: 'large', orderIndex: 1 },
        { name: 'American cheese', quantity: '2', unit: 'slices', orderIndex: 2 },
        { name: 'kaiser roll', quantity: '1', unit: 'piece', orderIndex: 3 },
        { name: 'butter', quantity: '1', unit: 'tbsp', orderIndex: 4 },
        { name: 'salt', quantity: '1', unit: 'pinch', orderIndex: 5 },
        { name: 'black pepper', quantity: '1', unit: 'pinch', orderIndex: 6 },
      ],
      steps: [
        { orderIndex: 0, text: 'Cook bacon in a skillet over medium heat until crispy. Set aside on paper towels.', duration: 360, techniqueTag: 'fry' },
        { orderIndex: 1, text: 'Scramble eggs in the bacon fat with a little butter. Season with salt and pepper. Keep them soft and slightly wet.', duration: 120, techniqueTag: 'scramble' },
        { orderIndex: 2, text: 'Slice the kaiser roll and toast it lightly on the griddle.', duration: 60, techniqueTag: 'toast' },
        { orderIndex: 3, text: 'Layer eggs on the bottom roll, top with cheese slices and bacon. Close the roll and press gently. The residual heat will melt the cheese.', duration: 30, techniqueTag: 'assemble' },
      ],
    },
    {
      name: 'Dollar Slice Pepperoni Pizza',
      description: 'Thin-crust, foldable New York-style pepperoni pizza. Crispy bottom, tangy sauce, stretchy mozzarella.',
      prepTime: 120,
      cookTime: 15,
      servings: 8,
      calories: 285,
      protein: 12,
      carbs: 33,
      fat: 12,
      difficulty: 'INTERMEDIATE' as const,
      dietaryTags: [],
      cuisineType: 'ITALIAN' as const,
      mealType: 'DINNER' as const,
      imageStatus: 'COMPLETED' as const,
      scrapedFrom: 'curated',
      location: 'New York',
      latitude: 40.7128,
      longitude: -74.006,
      engagementLoves: 1950,
      engagementBookmarks: 870,
      engagementViews: 14200,
      isViral: true,
      velocityScore: 85.0,
      ingredients: [
        { name: 'bread flour', quantity: '500', unit: 'g', orderIndex: 0 },
        { name: 'water', quantity: '325', unit: 'ml', orderIndex: 1 },
        { name: 'instant yeast', quantity: '5', unit: 'g', orderIndex: 2 },
        { name: 'salt', quantity: '10', unit: 'g', orderIndex: 3 },
        { name: 'olive oil', quantity: '15', unit: 'ml', orderIndex: 4 },
        { name: 'crushed tomatoes', quantity: '400', unit: 'g', orderIndex: 5 },
        { name: 'mozzarella', quantity: '250', unit: 'g', orderIndex: 6 },
        { name: 'pepperoni', quantity: '100', unit: 'g', orderIndex: 7 },
      ],
      steps: [
        { orderIndex: 0, text: 'Mix flour, water, yeast, salt, and olive oil. Knead for 8 minutes until smooth and elastic. Cover and let rise for 1.5 hours.', duration: 6000, techniqueTag: 'knead' },
        { orderIndex: 1, text: 'Preheat oven to maximum (260°C / 500°F) with a baking steel or inverted sheet pan inside.', duration: 1800, techniqueTag: 'preheat' },
        { orderIndex: 2, text: 'Stretch dough into a thin 14-inch round. Transfer to a floured peel or parchment.', duration: 180, techniqueTag: 'stretch' },
        { orderIndex: 3, text: 'Spread crushed tomatoes evenly, leaving a small border. Top with shredded mozzarella and pepperoni slices.', duration: 120, techniqueTag: 'assemble' },
        { orderIndex: 4, text: 'Slide onto the hot steel/pan. Bake 10-12 minutes until crust is golden and cheese is bubbly with charred spots.', duration: 720, techniqueTag: 'bake' },
      ],
    },

    // ── London ────────────────────────────────────────────────────────
    {
      name: 'Full English Breakfast',
      description: 'The ultimate British fry-up: bacon, eggs, sausages, beans, toast, grilled tomatoes, and mushrooms.',
      prepTime: 10,
      cookTime: 25,
      servings: 2,
      calories: 780,
      protein: 42,
      carbs: 48,
      fat: 45,
      difficulty: 'BEGINNER' as const,
      dietaryTags: [],
      cuisineType: 'BRITISH' as const,
      mealType: 'BREAKFAST' as const,
      imageStatus: 'COMPLETED' as const,
      scrapedFrom: 'curated',
      location: 'London',
      latitude: 51.5074,
      longitude: -0.1278,
      engagementLoves: 2100,
      engagementBookmarks: 890,
      engagementViews: 15800,
      isViral: true,
      velocityScore: 88.0,
      ingredients: [
        { name: 'back bacon', quantity: '4', unit: 'rashers', orderIndex: 0 },
        { name: 'pork sausages', quantity: '4', unit: 'pieces', orderIndex: 1 },
        { name: 'eggs', quantity: '2', unit: 'large', orderIndex: 2 },
        { name: 'baked beans', quantity: '200', unit: 'g', orderIndex: 3 },
        { name: 'mushrooms', quantity: '100', unit: 'g', orderIndex: 4 },
        { name: 'tomatoes', quantity: '2', unit: 'halved', orderIndex: 5 },
        { name: 'bread', quantity: '2', unit: 'slices', orderIndex: 6 },
        { name: 'butter', quantity: '20', unit: 'g', orderIndex: 7 },
      ],
      steps: [
        { orderIndex: 0, text: 'Start sausages in a cold pan over medium heat. Cook for 12-15 minutes, turning regularly, until golden all over.', duration: 900, techniqueTag: 'fry' },
        { orderIndex: 1, text: 'Add bacon to the pan. Fry for 3-4 minutes each side. Push to one side. Add halved tomatoes cut-side down and mushrooms.', duration: 480, techniqueTag: 'fry' },
        { orderIndex: 2, text: 'Heat baked beans in a small saucepan over low heat.', duration: 300, techniqueTag: 'simmer' },
        { orderIndex: 3, text: 'Fry eggs in a little butter to your liking. Toast the bread.', duration: 180, techniqueTag: 'fry' },
        { orderIndex: 4, text: 'Plate everything together and serve immediately with a cup of strong tea.', duration: 60, techniqueTag: 'assemble' },
      ],
    },
    {
      name: 'Chicken Tikka Masala',
      description: 'Britain\'s unofficial national dish. Tender spiced chicken in a rich, creamy tomato sauce.',
      prepTime: 30,
      cookTime: 35,
      servings: 4,
      calories: 490,
      protein: 38,
      carbs: 18,
      fat: 28,
      difficulty: 'INTERMEDIATE' as const,
      dietaryTags: ['gluten-free'],
      cuisineType: 'BRITISH' as const,
      mealType: 'DINNER' as const,
      imageStatus: 'COMPLETED' as const,
      scrapedFrom: 'curated',
      location: 'London',
      latitude: 51.5074,
      longitude: -0.1278,
      engagementLoves: 3500,
      engagementBookmarks: 2100,
      engagementViews: 25000,
      isViral: true,
      velocityScore: 96.0,
      ingredients: [
        { name: 'chicken breast', quantity: '600', unit: 'g', orderIndex: 0 },
        { name: 'yogurt', quantity: '150', unit: 'g', orderIndex: 1 },
        { name: 'garam masala', quantity: '2', unit: 'tbsp', orderIndex: 2 },
        { name: 'cumin', quantity: '1', unit: 'tsp', orderIndex: 3 },
        { name: 'turmeric', quantity: '1', unit: 'tsp', orderIndex: 4 },
        { name: 'tomato paste', quantity: '2', unit: 'tbsp', orderIndex: 5 },
        { name: 'crushed tomatoes', quantity: '400', unit: 'g', orderIndex: 6 },
        { name: 'heavy cream', quantity: '200', unit: 'ml', orderIndex: 7 },
        { name: 'onions', quantity: '2', unit: 'medium', orderIndex: 8 },
        { name: 'garlic', quantity: '4', unit: 'cloves', orderIndex: 9 },
        { name: 'ginger', quantity: '1', unit: 'inch', orderIndex: 10 },
        { name: 'butter', quantity: '30', unit: 'g', orderIndex: 11 },
      ],
      steps: [
        { orderIndex: 0, text: 'Cut chicken into chunks. Marinate in yogurt, half the garam masala, cumin, turmeric, salt and pepper. Refrigerate 30 minutes (or overnight).', duration: 1800, techniqueTag: 'marinate' },
        { orderIndex: 1, text: 'Grill or pan-fry marinated chicken pieces over high heat until charred and cooked through. Set aside.', duration: 600, techniqueTag: 'grill' },
        { orderIndex: 2, text: 'Melt butter in a pan. Sauté diced onions until golden. Add minced garlic and ginger, cook 1 minute.', duration: 480, techniqueTag: 'sauté' },
        { orderIndex: 3, text: 'Add tomato paste, remaining garam masala, and crushed tomatoes. Simmer for 15 minutes until thickened.', duration: 900, techniqueTag: 'simmer' },
        { orderIndex: 4, text: 'Stir in heavy cream and the cooked chicken. Simmer gently for 5 minutes. Serve over basmati rice with naan.', duration: 300, techniqueTag: 'simmer' },
      ],
    },
    {
      name: 'Fish & Chips',
      description: 'Golden beer-battered cod with thick-cut chips. Served with mushy peas and malt vinegar.',
      prepTime: 20,
      cookTime: 30,
      servings: 4,
      calories: 680,
      protein: 32,
      carbs: 65,
      fat: 32,
      difficulty: 'INTERMEDIATE' as const,
      dietaryTags: [],
      cuisineType: 'BRITISH' as const,
      mealType: 'DINNER' as const,
      imageStatus: 'COMPLETED' as const,
      scrapedFrom: 'curated',
      location: 'London',
      latitude: 51.5074,
      longitude: -0.1278,
      engagementLoves: 1800,
      engagementBookmarks: 720,
      engagementViews: 12400,
      isViral: true,
      velocityScore: 82.0,
      ingredients: [
        { name: 'cod fillets', quantity: '4', unit: 'pieces', orderIndex: 0 },
        { name: 'flour', quantity: '200', unit: 'g', orderIndex: 1 },
        { name: 'beer', quantity: '250', unit: 'ml', orderIndex: 2 },
        { name: 'baking powder', quantity: '1', unit: 'tsp', orderIndex: 3 },
        { name: 'potatoes', quantity: '1', unit: 'kg', orderIndex: 4 },
        { name: 'vegetable oil', quantity: '1', unit: 'L', orderIndex: 5 },
        { name: 'salt', quantity: '1', unit: 'tbsp', orderIndex: 6 },
        { name: 'malt vinegar', quantity: '1', unit: 'tbsp', orderIndex: 7 },
      ],
      steps: [
        { orderIndex: 0, text: 'Peel potatoes and cut into thick chips. Soak in cold water for 30 minutes, then pat dry thoroughly.', duration: 2100, techniqueTag: 'prep' },
        { orderIndex: 1, text: 'Heat oil to 130°C. Blanch chips for 5-6 minutes until soft but not coloured. Drain and set aside.', duration: 480, techniqueTag: 'fry' },
        { orderIndex: 2, text: 'Mix flour, baking powder, salt, and cold beer into a smooth batter. Rest 10 minutes.', duration: 720, techniqueTag: 'mix' },
        { orderIndex: 3, text: 'Increase oil to 180°C. Dip dried cod fillets in batter, letting excess drip off. Fry 6-7 minutes until deep golden. Drain on a wire rack.', duration: 480, techniqueTag: 'fry' },
        { orderIndex: 4, text: 'Return chips to 180°C oil. Fry 3-4 minutes until golden and crispy. Season with salt immediately. Serve with malt vinegar.', duration: 240, techniqueTag: 'fry' },
      ],
    },

    // ── Istanbul ──────────────────────────────────────────────────────
    {
      name: 'Iskender Kebab',
      description: 'Thinly sliced döner over pide bread, drenched in tomato sauce and sizzling browned butter, with a dollop of yogurt.',
      prepTime: 30,
      cookTime: 45,
      servings: 4,
      calories: 620,
      protein: 45,
      carbs: 38,
      fat: 30,
      difficulty: 'ADVANCED' as const,
      dietaryTags: ['halal'],
      cuisineType: 'TURKISH' as const,
      mealType: 'DINNER' as const,
      imageStatus: 'COMPLETED' as const,
      scrapedFrom: 'curated',
      location: 'Istanbul',
      latitude: 41.0082,
      longitude: 28.9784,
      engagementLoves: 2600,
      engagementBookmarks: 1800,
      engagementViews: 19500,
      isViral: true,
      velocityScore: 91.0,
      ingredients: [
        { name: 'lamb', quantity: '500', unit: 'g', orderIndex: 0 },
        { name: 'pide bread', quantity: '2', unit: 'pieces', orderIndex: 1 },
        { name: 'yogurt', quantity: '200', unit: 'g', orderIndex: 2 },
        { name: 'tomato paste', quantity: '2', unit: 'tbsp', orderIndex: 3 },
        { name: 'tomatoes', quantity: '3', unit: 'medium', orderIndex: 4 },
        { name: 'butter', quantity: '80', unit: 'g', orderIndex: 5 },
        { name: 'red pepper flakes', quantity: '1', unit: 'tsp', orderIndex: 6 },
        { name: 'onions', quantity: '1', unit: 'large', orderIndex: 7 },
        { name: 'garlic', quantity: '3', unit: 'cloves', orderIndex: 8 },
      ],
      steps: [
        { orderIndex: 0, text: 'Season lamb slices with salt, pepper, and a pinch of cumin. Grill over high heat until charred and cooked, 2-3 minutes per side.', duration: 360, techniqueTag: 'grill' },
        { orderIndex: 1, text: 'Make the sauce: sauté grated onion and garlic in a bit of oil. Add grated tomatoes and tomato paste. Simmer 15 minutes until thick.', duration: 1020, techniqueTag: 'simmer' },
        { orderIndex: 2, text: 'Cut pide bread into bite-sized pieces. Arrange on a serving plate.', duration: 120, techniqueTag: 'prep' },
        { orderIndex: 3, text: 'Layer sliced grilled lamb over the bread. Ladle hot tomato sauce generously over the meat.', duration: 60, techniqueTag: 'assemble' },
        { orderIndex: 4, text: 'Brown butter in a small pan until foamy and nutty. Add red pepper flakes, swirl once, and pour sizzling over the plate. Serve with a generous spoon of thick yogurt on the side.', duration: 120, techniqueTag: 'sauce' },
      ],
    },
    {
      name: 'Menemen',
      description: 'Turkish scrambled eggs simmered with tomatoes, green peppers, and spices. A breakfast staple across Turkey.',
      prepTime: 5,
      cookTime: 15,
      servings: 2,
      calories: 280,
      protein: 14,
      carbs: 12,
      fat: 20,
      difficulty: 'BEGINNER' as const,
      dietaryTags: ['vegetarian', 'gluten-free'],
      cuisineType: 'TURKISH' as const,
      mealType: 'BREAKFAST' as const,
      imageStatus: 'COMPLETED' as const,
      scrapedFrom: 'curated',
      location: 'Istanbul',
      latitude: 41.0082,
      longitude: 28.9784,
      engagementLoves: 1400,
      engagementBookmarks: 650,
      engagementViews: 9800,
      isViral: true,
      velocityScore: 78.0,
      ingredients: [
        { name: 'eggs', quantity: '4', unit: 'large', orderIndex: 0 },
        { name: 'tomatoes', quantity: '3', unit: 'medium', orderIndex: 1 },
        { name: 'green peppers', quantity: '2', unit: 'pieces', orderIndex: 2 },
        { name: 'onions', quantity: '1', unit: 'small', orderIndex: 3 },
        { name: 'olive oil', quantity: '2', unit: 'tbsp', orderIndex: 4 },
        { name: 'red pepper flakes', quantity: '1', unit: 'tsp', orderIndex: 5 },
        { name: 'salt', quantity: '1', unit: 'tsp', orderIndex: 6 },
      ],
      steps: [
        { orderIndex: 0, text: 'Heat olive oil in a pan over medium heat. Sauté diced onion and chopped peppers until softened, about 3 minutes.', duration: 240, techniqueTag: 'sauté' },
        { orderIndex: 1, text: 'Add grated or diced tomatoes. Cook until juices reduce and mixture thickens, about 8 minutes. Season with salt and red pepper flakes.', duration: 480, techniqueTag: 'simmer' },
        { orderIndex: 2, text: 'Crack eggs directly into the pan. Gently stir to create soft curds mixed with the vegetables. Cook 2-3 minutes until eggs are just set but still creamy.', duration: 180, techniqueTag: 'scramble' },
        { orderIndex: 3, text: 'Serve immediately in the pan with crusty bread for dipping.', duration: 30, techniqueTag: 'serve' },
      ],
    },
    {
      name: 'Lahmacun',
      description: 'Paper-thin Turkish flatbread topped with spiced minced meat, herbs, and vegetables. Rolled with lemon and parsley.',
      prepTime: 40,
      cookTime: 8,
      servings: 6,
      calories: 320,
      protein: 18,
      carbs: 38,
      fat: 12,
      difficulty: 'INTERMEDIATE' as const,
      dietaryTags: ['halal'],
      cuisineType: 'TURKISH' as const,
      mealType: 'LUNCH' as const,
      imageStatus: 'COMPLETED' as const,
      scrapedFrom: 'curated',
      location: 'Istanbul',
      latitude: 41.0082,
      longitude: 28.9784,
      engagementLoves: 2200,
      engagementBookmarks: 1100,
      engagementViews: 16000,
      isViral: true,
      velocityScore: 87.0,
      ingredients: [
        { name: 'flour', quantity: '300', unit: 'g', orderIndex: 0 },
        { name: 'ground beef', quantity: '250', unit: 'g', orderIndex: 1 },
        { name: 'onions', quantity: '2', unit: 'medium', orderIndex: 2 },
        { name: 'tomatoes', quantity: '2', unit: 'medium', orderIndex: 3 },
        { name: 'bell peppers', quantity: '1', unit: 'piece', orderIndex: 4 },
        { name: 'parsley', quantity: '1', unit: 'bunch', orderIndex: 5 },
        { name: 'red pepper flakes', quantity: '1', unit: 'tbsp', orderIndex: 6 },
        { name: 'tomato paste', quantity: '1', unit: 'tbsp', orderIndex: 7 },
        { name: 'lemon', quantity: '1', unit: 'piece', orderIndex: 8 },
      ],
      steps: [
        { orderIndex: 0, text: 'Make dough: mix flour, water, salt, and a splash of oil. Knead until smooth. Rest 30 minutes.', duration: 2100, techniqueTag: 'knead' },
        { orderIndex: 1, text: 'Finely chop onions, tomatoes, pepper, and parsley. Mix with ground meat, tomato paste, red pepper flakes, salt, and pepper into a paste.', duration: 600, techniqueTag: 'mix' },
        { orderIndex: 2, text: 'Divide dough into 6 balls. Roll each paper-thin into an oval shape on a floured surface.', duration: 600, techniqueTag: 'roll' },
        { orderIndex: 3, text: 'Spread meat mixture thinly over each dough piece, reaching the edges.', duration: 300, techniqueTag: 'assemble' },
        { orderIndex: 4, text: 'Bake on the hottest oven setting (250°C+) for 6-8 minutes until edges are crispy and topping is cooked. Roll with parsley, lemon juice, and optional lettuce.', duration: 480, techniqueTag: 'bake' },
      ],
    },

    // ── Paris ─────────────────────────────────────────────────────────
    {
      name: 'Croque Monsieur',
      description: 'The iconic French grilled ham and cheese sandwich with creamy béchamel and melted Gruyère.',
      prepTime: 15,
      cookTime: 15,
      servings: 2,
      calories: 520,
      protein: 28,
      carbs: 32,
      fat: 32,
      difficulty: 'BEGINNER' as const,
      dietaryTags: [],
      cuisineType: 'FRENCH' as const,
      mealType: 'LUNCH' as const,
      imageStatus: 'COMPLETED' as const,
      scrapedFrom: 'curated',
      location: 'Paris',
      latitude: 48.8566,
      longitude: 2.3522,
      engagementLoves: 1600,
      engagementBookmarks: 780,
      engagementViews: 11200,
      isViral: true,
      velocityScore: 80.0,
      ingredients: [
        { name: 'bread', quantity: '4', unit: 'slices', orderIndex: 0 },
        { name: 'ham', quantity: '4', unit: 'slices', orderIndex: 1 },
        { name: 'Gruyère cheese', quantity: '150', unit: 'g', orderIndex: 2 },
        { name: 'butter', quantity: '30', unit: 'g', orderIndex: 3 },
        { name: 'flour', quantity: '20', unit: 'g', orderIndex: 4 },
        { name: 'milk', quantity: '200', unit: 'ml', orderIndex: 5 },
        { name: 'nutmeg', quantity: '1', unit: 'pinch', orderIndex: 6 },
      ],
      steps: [
        { orderIndex: 0, text: 'Make béchamel: melt butter, whisk in flour, cook 1 minute. Gradually add milk, stirring constantly until thick. Season with salt, pepper, and nutmeg.', duration: 480, techniqueTag: 'sauce' },
        { orderIndex: 1, text: 'Spread béchamel on each bread slice. Layer ham and half the grated Gruyère on two slices. Top with remaining bread.', duration: 180, techniqueTag: 'assemble' },
        { orderIndex: 2, text: 'Spread more béchamel on top of each sandwich. Pile remaining Gruyère on top.', duration: 60, techniqueTag: 'assemble' },
        { orderIndex: 3, text: 'Bake at 200°C (400°F) for 10-12 minutes until golden and bubbly. Let rest 2 minutes before serving.', duration: 720, techniqueTag: 'bake' },
      ],
    },
    {
      name: 'Ratatouille',
      description: 'Provençal vegetable stew with layers of zucchini, eggplant, tomatoes, and bell peppers in a fragrant herb sauce.',
      prepTime: 30,
      cookTime: 60,
      servings: 6,
      calories: 180,
      protein: 4,
      carbs: 22,
      fat: 9,
      difficulty: 'INTERMEDIATE' as const,
      dietaryTags: ['vegan', 'gluten-free'],
      cuisineType: 'FRENCH' as const,
      mealType: 'DINNER' as const,
      imageStatus: 'COMPLETED' as const,
      scrapedFrom: 'curated',
      location: 'Paris',
      latitude: 48.8566,
      longitude: 2.3522,
      engagementLoves: 2400,
      engagementBookmarks: 1300,
      engagementViews: 17000,
      isViral: true,
      velocityScore: 89.0,
      ingredients: [
        { name: 'zucchini', quantity: '2', unit: 'medium', orderIndex: 0 },
        { name: 'eggplant', quantity: '1', unit: 'large', orderIndex: 1 },
        { name: 'bell peppers', quantity: '2', unit: 'pieces', orderIndex: 2 },
        { name: 'tomatoes', quantity: '4', unit: 'medium', orderIndex: 3 },
        { name: 'onions', quantity: '1', unit: 'large', orderIndex: 4 },
        { name: 'garlic', quantity: '4', unit: 'cloves', orderIndex: 5 },
        { name: 'olive oil', quantity: '60', unit: 'ml', orderIndex: 6 },
        { name: 'thyme', quantity: '4', unit: 'sprigs', orderIndex: 7 },
        { name: 'basil', quantity: '1', unit: 'bunch', orderIndex: 8 },
      ],
      steps: [
        { orderIndex: 0, text: 'Dice onion and peppers. Sauté in olive oil until soft. Add minced garlic, cook 1 minute.', duration: 480, techniqueTag: 'sauté' },
        { orderIndex: 1, text: 'Add diced tomatoes. Cook down into a sauce for 10 minutes. Season with salt, pepper, and thyme. Spread in an oven dish.', duration: 720, techniqueTag: 'simmer' },
        { orderIndex: 2, text: 'Slice zucchini and eggplant into thin rounds. Arrange alternating slices in a spiral pattern over the sauce.', duration: 600, techniqueTag: 'assemble' },
        { orderIndex: 3, text: 'Drizzle with olive oil, season with salt and pepper. Cover with foil and bake at 190°C (375°F) for 40 minutes.', duration: 2400, techniqueTag: 'bake' },
        { orderIndex: 4, text: 'Remove foil and bake 15 more minutes until vegetables are tender and edges caramelize. Garnish with fresh basil.', duration: 900, techniqueTag: 'bake' },
      ],
    },

    // ── Tokyo ─────────────────────────────────────────────────────────
    {
      name: 'Tonkotsu Ramen',
      description: 'Rich, milky pork bone broth ramen with chashu pork, soft-boiled egg, bamboo shoots, and green onions.',
      prepTime: 30,
      cookTime: 720,
      servings: 4,
      calories: 650,
      protein: 38,
      carbs: 62,
      fat: 28,
      difficulty: 'ADVANCED' as const,
      dietaryTags: [],
      cuisineType: 'JAPANESE' as const,
      mealType: 'DINNER' as const,
      imageStatus: 'COMPLETED' as const,
      scrapedFrom: 'curated',
      location: 'Tokyo',
      latitude: 35.6762,
      longitude: 139.6503,
      engagementLoves: 4100,
      engagementBookmarks: 2800,
      engagementViews: 32000,
      isViral: true,
      velocityScore: 98.0,
      ingredients: [
        { name: 'pork bones', quantity: '1.5', unit: 'kg', orderIndex: 0 },
        { name: 'pork belly', quantity: '500', unit: 'g', orderIndex: 1 },
        { name: 'ramen noodles', quantity: '400', unit: 'g', orderIndex: 2 },
        { name: 'eggs', quantity: '4', unit: 'large', orderIndex: 3 },
        { name: 'soy sauce', quantity: '100', unit: 'ml', orderIndex: 4 },
        { name: 'ginger', quantity: '1', unit: 'large piece', orderIndex: 5 },
        { name: 'garlic', quantity: '8', unit: 'cloves', orderIndex: 6 },
        { name: 'scallions', quantity: '4', unit: 'stalks', orderIndex: 7 },
        { name: 'sesame oil', quantity: '1', unit: 'tbsp', orderIndex: 8 },
      ],
      steps: [
        { orderIndex: 0, text: 'Blanch pork bones in boiling water for 10 minutes. Drain, rinse, and scrub clean. This removes impurities for a cleaner broth.', duration: 900, techniqueTag: 'blanch' },
        { orderIndex: 1, text: 'Return bones to pot with halved ginger and garlic. Cover with water. Bring to a rolling boil, then reduce to a vigorous simmer. Cook 10-12 hours, adding water as needed to keep bones covered.', duration: 43200, techniqueTag: 'simmer' },
        { orderIndex: 2, text: 'Make chashu: roll pork belly, tie with string. Sear all sides. Braise in soy sauce, mirin, sake, sugar, ginger, and garlic for 2 hours until tender.', duration: 7500, techniqueTag: 'braise' },
        { orderIndex: 3, text: 'Soft-boil eggs (6.5 minutes). Peel and marinate in leftover chashu braising liquid for at least 2 hours.', duration: 7500, techniqueTag: 'boil' },
        { orderIndex: 4, text: 'Strain broth and season with soy sauce and sesame oil. Cook ramen noodles per package directions. Assemble bowls: noodles, hot broth, sliced chashu, halved egg, sliced scallions.', duration: 600, techniqueTag: 'assemble' },
      ],
    },
    {
      name: 'Okonomiyaki',
      description: 'Savory Japanese cabbage pancake loaded with your choice of toppings, drizzled with special sauce and Kewpie mayo.',
      prepTime: 15,
      cookTime: 15,
      servings: 2,
      calories: 420,
      protein: 18,
      carbs: 45,
      fat: 19,
      difficulty: 'BEGINNER' as const,
      dietaryTags: [],
      cuisineType: 'JAPANESE' as const,
      mealType: 'DINNER' as const,
      imageStatus: 'COMPLETED' as const,
      scrapedFrom: 'curated',
      location: 'Tokyo',
      latitude: 35.6762,
      longitude: 139.6503,
      engagementLoves: 1800,
      engagementBookmarks: 920,
      engagementViews: 13500,
      isViral: true,
      velocityScore: 83.0,
      ingredients: [
        { name: 'cabbage', quantity: '300', unit: 'g', orderIndex: 0 },
        { name: 'flour', quantity: '100', unit: 'g', orderIndex: 1 },
        { name: 'eggs', quantity: '2', unit: 'large', orderIndex: 2 },
        { name: 'bacon', quantity: '4', unit: 'strips', orderIndex: 3 },
        { name: 'scallions', quantity: '2', unit: 'stalks', orderIndex: 4 },
        { name: 'Kewpie mayonnaise', quantity: '2', unit: 'tbsp', orderIndex: 5 },
        { name: 'Worcestershire sauce', quantity: '2', unit: 'tbsp', orderIndex: 6 },
        { name: 'bonito flakes', quantity: '5', unit: 'g', orderIndex: 7 },
      ],
      steps: [
        { orderIndex: 0, text: 'Finely shred cabbage. Mix flour, eggs, a splash of water, and a pinch of dashi powder into a batter. Fold in cabbage and sliced scallions.', duration: 360, techniqueTag: 'mix' },
        { orderIndex: 1, text: 'Heat an oiled pan or griddle over medium heat. Pour batter into a thick round pancake shape. Lay bacon strips on top.', duration: 120, techniqueTag: 'fry' },
        { orderIndex: 2, text: 'Cook 5-6 minutes until bottom is golden. Carefully flip and cook another 5 minutes until cooked through and crispy.', duration: 660, techniqueTag: 'fry' },
        { orderIndex: 3, text: 'Drizzle with okonomiyaki sauce (or Worcestershire) and Kewpie mayo in zigzag lines. Top with bonito flakes and serve immediately.', duration: 60, techniqueTag: 'garnish' },
      ],
    },

    // ── Mexico City ───────────────────────────────────────────────────
    {
      name: 'Tacos al Pastor',
      description: 'Spit-grilled marinated pork tacos inspired by Lebanese shawarma. Topped with pineapple, cilantro, and onion.',
      prepTime: 60,
      cookTime: 30,
      servings: 6,
      calories: 380,
      protein: 25,
      carbs: 35,
      fat: 16,
      difficulty: 'INTERMEDIATE' as const,
      dietaryTags: [],
      cuisineType: 'MEXICAN' as const,
      mealType: 'DINNER' as const,
      imageStatus: 'COMPLETED' as const,
      scrapedFrom: 'curated',
      location: 'Mexico City',
      latitude: 19.4326,
      longitude: -99.1332,
      engagementLoves: 3800,
      engagementBookmarks: 2200,
      engagementViews: 28000,
      isViral: true,
      velocityScore: 97.0,
      ingredients: [
        { name: 'pork shoulder', quantity: '800', unit: 'g', orderIndex: 0 },
        { name: 'dried guajillo chiles', quantity: '4', unit: 'pieces', orderIndex: 1 },
        { name: 'pineapple', quantity: '200', unit: 'g', orderIndex: 2 },
        { name: 'achiote paste', quantity: '2', unit: 'tbsp', orderIndex: 3 },
        { name: 'corn tortillas', quantity: '12', unit: 'pieces', orderIndex: 4 },
        { name: 'onions', quantity: '1', unit: 'medium', orderIndex: 5 },
        { name: 'cilantro', quantity: '1', unit: 'bunch', orderIndex: 6 },
        { name: 'lime', quantity: '2', unit: 'pieces', orderIndex: 7 },
      ],
      steps: [
        { orderIndex: 0, text: 'Toast guajillo chiles in a dry pan, then rehydrate in hot water for 15 minutes. Blend with achiote paste, vinegar, garlic, cumin, oregano, and pineapple juice into a smooth marinade.', duration: 1200, techniqueTag: 'blend' },
        { orderIndex: 1, text: 'Slice pork shoulder thin. Coat in marinade and refrigerate at least 1 hour (overnight is best).', duration: 3600, techniqueTag: 'marinate' },
        { orderIndex: 2, text: 'Grill or pan-sear marinated pork over high heat in batches until charred and caramelized. Chop finely. Grill pineapple slices until charred and dice.', duration: 900, techniqueTag: 'grill' },
        { orderIndex: 3, text: 'Warm corn tortillas on a dry griddle. Double them up for strength.', duration: 180, techniqueTag: 'toast' },
        { orderIndex: 4, text: 'Assemble tacos: pile chopped pork on tortillas, top with diced pineapple, minced onion, fresh cilantro, and a generous squeeze of lime.', duration: 180, techniqueTag: 'assemble' },
      ],
    },
    {
      name: 'Churros con Chocolate',
      description: 'Crispy fried dough sticks coated in cinnamon sugar, served with rich thick hot chocolate for dipping.',
      prepTime: 15,
      cookTime: 20,
      servings: 4,
      calories: 380,
      protein: 5,
      carbs: 48,
      fat: 20,
      difficulty: 'INTERMEDIATE' as const,
      dietaryTags: ['vegetarian'],
      cuisineType: 'MEXICAN' as const,
      mealType: 'DESSERT' as const,
      imageStatus: 'COMPLETED' as const,
      scrapedFrom: 'curated',
      location: 'Mexico City',
      latitude: 19.4326,
      longitude: -99.1332,
      engagementLoves: 2700,
      engagementBookmarks: 1400,
      engagementViews: 20000,
      isViral: true,
      velocityScore: 90.0,
      ingredients: [
        { name: 'water', quantity: '250', unit: 'ml', orderIndex: 0 },
        { name: 'butter', quantity: '60', unit: 'g', orderIndex: 1 },
        { name: 'flour', quantity: '150', unit: 'g', orderIndex: 2 },
        { name: 'eggs', quantity: '2', unit: 'large', orderIndex: 3 },
        { name: 'sugar', quantity: '100', unit: 'g', orderIndex: 4 },
        { name: 'cinnamon', quantity: '2', unit: 'tsp', orderIndex: 5 },
        { name: 'dark chocolate', quantity: '150', unit: 'g', orderIndex: 6 },
        { name: 'milk', quantity: '200', unit: 'ml', orderIndex: 7 },
        { name: 'vegetable oil', quantity: '500', unit: 'ml', orderIndex: 8 },
      ],
      steps: [
        { orderIndex: 0, text: 'Bring water, butter, sugar (1 tbsp), and salt to a boil. Remove from heat, stir in flour all at once until a ball forms. Cool 5 minutes, then beat in eggs one at a time.', duration: 600, techniqueTag: 'mix' },
        { orderIndex: 1, text: 'Transfer dough to a piping bag with a star tip. Heat oil to 180°C (350°F).', duration: 300, techniqueTag: 'prep' },
        { orderIndex: 2, text: 'Pipe 15cm strips directly into the hot oil. Fry in batches for 3-4 minutes, turning once, until golden brown and crispy. Drain on paper towels.', duration: 600, techniqueTag: 'fry' },
        { orderIndex: 3, text: 'Mix remaining sugar with cinnamon. Roll hot churros in the cinnamon sugar to coat.', duration: 120, techniqueTag: 'coat' },
        { orderIndex: 4, text: 'Make chocolate sauce: heat milk with chopped dark chocolate, stirring until smooth and thick. Serve churros warm with chocolate for dipping.', duration: 300, techniqueTag: 'melt' },
      ],
    },

    // ── Bangkok ───────────────────────────────────────────────────────
    {
      name: 'Pad Thai',
      description: 'Thailand\'s most famous stir-fried noodle dish with shrimp, tofu, peanuts, bean sprouts, and tamarind sauce.',
      prepTime: 20,
      cookTime: 10,
      servings: 2,
      calories: 440,
      protein: 22,
      carbs: 52,
      fat: 18,
      difficulty: 'INTERMEDIATE' as const,
      dietaryTags: ['gluten-free'],
      cuisineType: 'THAI' as const,
      mealType: 'DINNER' as const,
      imageStatus: 'COMPLETED' as const,
      scrapedFrom: 'curated',
      location: 'Bangkok',
      latitude: 13.7563,
      longitude: 100.5018,
      engagementLoves: 3100,
      engagementBookmarks: 1900,
      engagementViews: 24000,
      isViral: true,
      velocityScore: 94.0,
      ingredients: [
        { name: 'rice noodles', quantity: '200', unit: 'g', orderIndex: 0 },
        { name: 'shrimp', quantity: '150', unit: 'g', orderIndex: 1 },
        { name: 'tofu', quantity: '100', unit: 'g', orderIndex: 2 },
        { name: 'eggs', quantity: '2', unit: 'large', orderIndex: 3 },
        { name: 'bean sprouts', quantity: '100', unit: 'g', orderIndex: 4 },
        { name: 'peanuts', quantity: '50', unit: 'g', orderIndex: 5 },
        { name: 'tamarind paste', quantity: '2', unit: 'tbsp', orderIndex: 6 },
        { name: 'fish sauce', quantity: '2', unit: 'tbsp', orderIndex: 7 },
        { name: 'sugar', quantity: '1', unit: 'tbsp', orderIndex: 8 },
        { name: 'lime', quantity: '1', unit: 'piece', orderIndex: 9 },
        { name: 'scallions', quantity: '2', unit: 'stalks', orderIndex: 10 },
      ],
      steps: [
        { orderIndex: 0, text: 'Soak rice noodles in warm water for 30 minutes until pliable. Drain well. Mix tamarind paste, fish sauce, and sugar into a sauce.', duration: 1920, techniqueTag: 'prep' },
        { orderIndex: 1, text: 'Heat a wok over high heat until smoking. Stir-fry cubed tofu until golden. Add shrimp, cook until pink. Push to the side.', duration: 240, techniqueTag: 'stir-fry' },
        { orderIndex: 2, text: 'Crack eggs into the wok. Scramble briefly, then add drained noodles and sauce. Toss everything together for 2-3 minutes.', duration: 180, techniqueTag: 'stir-fry' },
        { orderIndex: 3, text: 'Add bean sprouts and scallion pieces. Toss for 30 seconds to wilt slightly.', duration: 30, techniqueTag: 'toss' },
        { orderIndex: 4, text: 'Serve topped with crushed peanuts, extra bean sprouts, and lime wedges on the side.', duration: 60, techniqueTag: 'garnish' },
      ],
    },
    {
      name: 'Green Curry with Chicken',
      description: 'Fragrant Thai green curry with tender chicken, bamboo shoots, Thai basil, and creamy coconut milk.',
      prepTime: 15,
      cookTime: 25,
      servings: 4,
      calories: 480,
      protein: 32,
      carbs: 15,
      fat: 34,
      difficulty: 'BEGINNER' as const,
      dietaryTags: ['gluten-free'],
      cuisineType: 'THAI' as const,
      mealType: 'DINNER' as const,
      imageStatus: 'COMPLETED' as const,
      scrapedFrom: 'curated',
      location: 'Bangkok',
      latitude: 13.7563,
      longitude: 100.5018,
      engagementLoves: 2000,
      engagementBookmarks: 1050,
      engagementViews: 14800,
      isViral: true,
      velocityScore: 84.0,
      ingredients: [
        { name: 'chicken thighs', quantity: '500', unit: 'g', orderIndex: 0 },
        { name: 'coconut milk', quantity: '400', unit: 'ml', orderIndex: 1 },
        { name: 'green curry paste', quantity: '3', unit: 'tbsp', orderIndex: 2 },
        { name: 'bamboo shoots', quantity: '100', unit: 'g', orderIndex: 3 },
        { name: 'Thai basil', quantity: '1', unit: 'handful', orderIndex: 4 },
        { name: 'fish sauce', quantity: '2', unit: 'tbsp', orderIndex: 5 },
        { name: 'sugar', quantity: '1', unit: 'tsp', orderIndex: 6 },
        { name: 'Thai chili', quantity: '2', unit: 'pieces', orderIndex: 7 },
        { name: 'kaffir lime leaves', quantity: '3', unit: 'pieces', orderIndex: 8 },
      ],
      steps: [
        { orderIndex: 0, text: 'Scoop the thick cream from the top of the coconut milk can. Heat in a wok until it splits and oil separates. Fry curry paste in the oil for 2 minutes until fragrant.', duration: 300, techniqueTag: 'fry' },
        { orderIndex: 1, text: 'Add sliced chicken. Stir-fry until sealed on all sides, about 3 minutes.', duration: 180, techniqueTag: 'stir-fry' },
        { orderIndex: 2, text: 'Pour in remaining coconut milk. Add bamboo shoots and torn kaffir lime leaves. Simmer for 15 minutes until chicken is cooked.', duration: 900, techniqueTag: 'simmer' },
        { orderIndex: 3, text: 'Season with fish sauce and sugar. Add sliced Thai chilies for extra heat. Stir in Thai basil just before serving.', duration: 60, techniqueTag: 'season' },
        { orderIndex: 4, text: 'Serve over steamed jasmine rice.', duration: 30, techniqueTag: 'serve' },
      ],
    },

    // ── Seoul ─────────────────────────────────────────────────────────
    {
      name: 'Bibimbap',
      description: 'Korean rice bowl topped with assorted sautéed vegetables, spicy gochujang, a fried egg, and optional beef.',
      prepTime: 30,
      cookTime: 20,
      servings: 2,
      calories: 520,
      protein: 24,
      carbs: 68,
      fat: 16,
      difficulty: 'INTERMEDIATE' as const,
      dietaryTags: ['gluten-free'],
      cuisineType: 'KOREAN' as const,
      mealType: 'DINNER' as const,
      imageStatus: 'COMPLETED' as const,
      scrapedFrom: 'curated',
      location: 'Seoul',
      latitude: 37.5665,
      longitude: 126.978,
      engagementLoves: 2900,
      engagementBookmarks: 1700,
      engagementViews: 21000,
      isViral: true,
      velocityScore: 93.0,
      ingredients: [
        { name: 'rice', quantity: '300', unit: 'g', orderIndex: 0 },
        { name: 'spinach', quantity: '150', unit: 'g', orderIndex: 1 },
        { name: 'carrots', quantity: '1', unit: 'medium', orderIndex: 2 },
        { name: 'zucchini', quantity: '1', unit: 'small', orderIndex: 3 },
        { name: 'mushrooms', quantity: '100', unit: 'g', orderIndex: 4 },
        { name: 'bean sprouts', quantity: '100', unit: 'g', orderIndex: 5 },
        { name: 'eggs', quantity: '2', unit: 'large', orderIndex: 6 },
        { name: 'gochujang', quantity: '2', unit: 'tbsp', orderIndex: 7 },
        { name: 'sesame oil', quantity: '2', unit: 'tbsp', orderIndex: 8 },
        { name: 'soy sauce', quantity: '1', unit: 'tbsp', orderIndex: 9 },
      ],
      steps: [
        { orderIndex: 0, text: 'Cook rice and keep warm. Blanch spinach and bean sprouts separately, squeeze dry, and season each with sesame oil, salt, and garlic.', duration: 900, techniqueTag: 'prep' },
        { orderIndex: 1, text: 'Julienne carrots and zucchini. Sauté each separately in a little oil with a pinch of salt until just tender. Sauté sliced mushrooms until golden.', duration: 600, techniqueTag: 'sauté' },
        { orderIndex: 2, text: 'Fry eggs sunny-side up in sesame oil until whites are set but yolks are still runny.', duration: 180, techniqueTag: 'fry' },
        { orderIndex: 3, text: 'Assemble bowls: place rice in the center. Arrange each vegetable in separate sections around the rice in a colorful pattern. Top with fried egg.', duration: 120, techniqueTag: 'assemble' },
        { orderIndex: 4, text: 'Serve with a generous dollop of gochujang on top. Mix everything together vigorously before eating.', duration: 30, techniqueTag: 'serve' },
      ],
    },

    // ── Rome ──────────────────────────────────────────────────────────
    {
      name: 'Cacio e Pepe',
      description: 'Roman pasta perfection: just pecorino, black pepper, and pasta water transformed into a silky, peppery sauce.',
      prepTime: 5,
      cookTime: 15,
      servings: 2,
      calories: 480,
      protein: 18,
      carbs: 58,
      fat: 20,
      difficulty: 'INTERMEDIATE' as const,
      dietaryTags: ['vegetarian'],
      cuisineType: 'ITALIAN' as const,
      mealType: 'DINNER' as const,
      imageStatus: 'COMPLETED' as const,
      scrapedFrom: 'curated',
      location: 'Rome',
      latitude: 41.9028,
      longitude: 12.4964,
      engagementLoves: 3600,
      engagementBookmarks: 2400,
      engagementViews: 27000,
      isViral: true,
      velocityScore: 96.5,
      ingredients: [
        { name: 'tonnarelli or spaghetti', quantity: '200', unit: 'g', orderIndex: 0 },
        { name: 'Pecorino Romano', quantity: '150', unit: 'g', orderIndex: 1 },
        { name: 'black pepper', quantity: '2', unit: 'tbsp', orderIndex: 2 },
        { name: 'salt', quantity: '1', unit: 'tbsp', orderIndex: 3 },
      ],
      steps: [
        { orderIndex: 0, text: 'Toast whole black peppercorns in a dry pan until fragrant. Crack coarsely with a mortar and pestle.', duration: 120, techniqueTag: 'toast' },
        { orderIndex: 1, text: 'Boil pasta in well-salted water until 1 minute short of al dente. Reserve 2 cups pasta water before draining.', duration: 600, techniqueTag: 'boil' },
        { orderIndex: 2, text: 'Finely grate Pecorino Romano. Mix half with a few tablespoons of pasta water to create a smooth paste.', duration: 120, techniqueTag: 'mix' },
        { orderIndex: 3, text: 'Add cracked pepper to a large pan with a splash of pasta water. Add drained pasta and toss over medium-low heat, adding pasta water gradually.', duration: 120, techniqueTag: 'toss' },
        { orderIndex: 4, text: 'Remove from heat. Add cheese paste, tossing vigorously to create a creamy emulsion. Add remaining cheese, adjusting with pasta water until silky. Serve immediately with extra pepper.', duration: 120, techniqueTag: 'emulsify' },
      ],
    },

    // ── Mumbai ────────────────────────────────────────────────────────
    {
      name: 'Butter Chicken (Murgh Makhani)',
      description: 'Tender tandoori-spiced chicken in a luscious, velvety tomato-butter sauce. The ultimate Indian comfort food.',
      prepTime: 30,
      cookTime: 40,
      servings: 4,
      calories: 510,
      protein: 36,
      carbs: 14,
      fat: 35,
      difficulty: 'INTERMEDIATE' as const,
      dietaryTags: ['gluten-free'],
      cuisineType: 'INDIAN' as const,
      mealType: 'DINNER' as const,
      imageStatus: 'COMPLETED' as const,
      scrapedFrom: 'curated',
      location: 'Mumbai',
      latitude: 19.076,
      longitude: 72.8777,
      engagementLoves: 3400,
      engagementBookmarks: 2000,
      engagementViews: 26000,
      isViral: true,
      velocityScore: 95.5,
      ingredients: [
        { name: 'chicken thighs', quantity: '600', unit: 'g', orderIndex: 0 },
        { name: 'yogurt', quantity: '100', unit: 'g', orderIndex: 1 },
        { name: 'butter', quantity: '60', unit: 'g', orderIndex: 2 },
        { name: 'crushed tomatoes', quantity: '400', unit: 'g', orderIndex: 3 },
        { name: 'heavy cream', quantity: '150', unit: 'ml', orderIndex: 4 },
        { name: 'garam masala', quantity: '2', unit: 'tsp', orderIndex: 5 },
        { name: 'turmeric', quantity: '1', unit: 'tsp', orderIndex: 6 },
        { name: 'chili powder', quantity: '1', unit: 'tsp', orderIndex: 7 },
        { name: 'garlic', quantity: '4', unit: 'cloves', orderIndex: 8 },
        { name: 'ginger', quantity: '1', unit: 'inch', orderIndex: 9 },
        { name: 'sugar', quantity: '1', unit: 'tsp', orderIndex: 10 },
        { name: 'dried fenugreek leaves', quantity: '1', unit: 'tbsp', orderIndex: 11 },
      ],
      steps: [
        { orderIndex: 0, text: 'Marinate chicken in yogurt, turmeric, chili powder, garam masala, and salt for at least 30 minutes.', duration: 1800, techniqueTag: 'marinate' },
        { orderIndex: 1, text: 'Grill or broil chicken until charred on edges and cooked through. Cut into bite-sized pieces.', duration: 600, techniqueTag: 'grill' },
        { orderIndex: 2, text: 'Melt butter in a heavy pan. Add minced garlic and ginger, sauté 1 minute. Add crushed tomatoes and simmer 20 minutes until thick.', duration: 1320, techniqueTag: 'simmer' },
        { orderIndex: 3, text: 'Blend the sauce until smooth (or use an immersion blender). Return to pan and stir in cream, sugar, and crush dried fenugreek leaves between your palms as you add them.', duration: 180, techniqueTag: 'blend' },
        { orderIndex: 4, text: 'Add grilled chicken to the sauce. Simmer gently for 10 minutes. Adjust salt. Finish with a swirl of cream and serve with naan or basmati rice.', duration: 600, techniqueTag: 'simmer' },
      ],
    },

    // ── Barcelona ─────────────────────────────────────────────────────
    {
      name: 'Patatas Bravas',
      description: 'Crispy fried potato cubes with a smoky, spicy tomato sauce and garlic aioli. Spain\'s most beloved tapa.',
      prepTime: 15,
      cookTime: 25,
      servings: 4,
      calories: 320,
      protein: 5,
      carbs: 38,
      fat: 18,
      difficulty: 'BEGINNER' as const,
      dietaryTags: ['vegan', 'gluten-free'],
      cuisineType: 'SPANISH' as const,
      mealType: 'APPETIZER' as const,
      imageStatus: 'COMPLETED' as const,
      scrapedFrom: 'curated',
      location: 'Barcelona',
      latitude: 41.3874,
      longitude: 2.1686,
      engagementLoves: 1900,
      engagementBookmarks: 850,
      engagementViews: 13000,
      isViral: true,
      velocityScore: 81.0,
      ingredients: [
        { name: 'potatoes', quantity: '600', unit: 'g', orderIndex: 0 },
        { name: 'olive oil', quantity: '100', unit: 'ml', orderIndex: 1 },
        { name: 'crushed tomatoes', quantity: '200', unit: 'g', orderIndex: 2 },
        { name: 'smoked paprika', quantity: '1', unit: 'tsp', orderIndex: 3 },
        { name: 'cayenne', quantity: '0.5', unit: 'tsp', orderIndex: 4 },
        { name: 'garlic', quantity: '3', unit: 'cloves', orderIndex: 5 },
        { name: 'mayonnaise', quantity: '100', unit: 'g', orderIndex: 6 },
        { name: 'lemon', quantity: '0.5', unit: 'piece', orderIndex: 7 },
      ],
      steps: [
        { orderIndex: 0, text: 'Peel and cut potatoes into rough 3cm cubes. Parboil in salted water for 8 minutes until just tender. Drain and let steam dry.', duration: 660, techniqueTag: 'boil' },
        { orderIndex: 1, text: 'Make bravas sauce: sauté minced garlic in olive oil. Add crushed tomatoes, smoked paprika, cayenne, salt. Simmer 10 minutes until thick.', duration: 720, techniqueTag: 'simmer' },
        { orderIndex: 2, text: 'Make aioli: mix mayonnaise with minced garlic, lemon juice, and a pinch of salt.', duration: 120, techniqueTag: 'mix' },
        { orderIndex: 3, text: 'Fry potatoes in olive oil (or deep-fry at 180°C) until golden and crispy all over, about 8-10 minutes.', duration: 600, techniqueTag: 'fry' },
        { orderIndex: 4, text: 'Pile crispy potatoes on a plate. Drizzle generously with bravas sauce and dots of garlic aioli. Serve with toothpicks.', duration: 60, techniqueTag: 'assemble' },
      ],
    },

    // ── Marrakech ─────────────────────────────────────────────────────
    {
      name: 'Chicken Tagine with Preserved Lemons',
      description: 'Slow-cooked Moroccan chicken with preserved lemons, olives, and fragrant spices in a conical clay pot.',
      prepTime: 20,
      cookTime: 60,
      servings: 4,
      calories: 420,
      protein: 35,
      carbs: 12,
      fat: 26,
      difficulty: 'INTERMEDIATE' as const,
      dietaryTags: ['gluten-free', 'halal'],
      cuisineType: 'MOROCCAN' as const,
      mealType: 'DINNER' as const,
      imageStatus: 'COMPLETED' as const,
      scrapedFrom: 'curated',
      location: 'Marrakech',
      latitude: 31.6295,
      longitude: -7.9811,
      engagementLoves: 1500,
      engagementBookmarks: 890,
      engagementViews: 10500,
      isViral: true,
      velocityScore: 79.0,
      ingredients: [
        { name: 'chicken thighs', quantity: '8', unit: 'pieces', orderIndex: 0 },
        { name: 'preserved lemon', quantity: '1', unit: 'large', orderIndex: 1 },
        { name: 'green olives', quantity: '150', unit: 'g', orderIndex: 2 },
        { name: 'onions', quantity: '2', unit: 'large', orderIndex: 3 },
        { name: 'garlic', quantity: '4', unit: 'cloves', orderIndex: 4 },
        { name: 'ginger', quantity: '1', unit: 'tsp ground', orderIndex: 5 },
        { name: 'turmeric', quantity: '1', unit: 'tsp', orderIndex: 6 },
        { name: 'saffron', quantity: '1', unit: 'pinch', orderIndex: 7 },
        { name: 'cilantro', quantity: '1', unit: 'bunch', orderIndex: 8 },
        { name: 'olive oil', quantity: '3', unit: 'tbsp', orderIndex: 9 },
      ],
      steps: [
        { orderIndex: 0, text: 'Season chicken with salt, ginger, turmeric, and saffron. Heat olive oil in a tagine or heavy pot. Brown chicken on all sides. Set aside.', duration: 600, techniqueTag: 'sear' },
        { orderIndex: 1, text: 'In the same pot, sauté sliced onions until very soft and golden. Add garlic, cook 1 minute. Return chicken to the pot.', duration: 600, techniqueTag: 'sauté' },
        { orderIndex: 2, text: 'Add water to come halfway up the chicken. Tuck in cilantro stems. Cover and simmer gently for 40 minutes.', duration: 2400, techniqueTag: 'braise' },
        { orderIndex: 3, text: 'Rinse preserved lemon and discard pulp. Slice the peel into strips. Add to the tagine along with olives. Cook 15 more minutes uncovered to reduce sauce.', duration: 900, techniqueTag: 'simmer' },
        { orderIndex: 4, text: 'Garnish with fresh cilantro leaves. Serve with fluffy couscous or crusty bread to soak up the sauce.', duration: 60, techniqueTag: 'garnish' },
      ],
    },

    // ── Vilnius (user's city) ─────────────────────────────────────────
    {
      name: 'Cepelinai (Zeppelin Dumplings)',
      description: 'Lithuania\'s national dish: massive potato dumplings stuffed with seasoned meat, served with sour cream and bacon bits.',
      prepTime: 45,
      cookTime: 30,
      servings: 4,
      calories: 580,
      protein: 25,
      carbs: 65,
      fat: 24,
      difficulty: 'ADVANCED' as const,
      dietaryTags: ['gluten-free'],
      cuisineType: 'OTHER' as const,
      mealType: 'DINNER' as const,
      imageStatus: 'COMPLETED' as const,
      scrapedFrom: 'curated',
      location: 'Vilnius',
      latitude: 54.6872,
      longitude: 25.2797,
      engagementLoves: 1100,
      engagementBookmarks: 620,
      engagementViews: 7500,
      isViral: true,
      velocityScore: 72.0,
      ingredients: [
        { name: 'potatoes', quantity: '1.5', unit: 'kg', orderIndex: 0 },
        { name: 'ground pork', quantity: '300', unit: 'g', orderIndex: 1 },
        { name: 'onions', quantity: '2', unit: 'medium', orderIndex: 2 },
        { name: 'sour cream', quantity: '200', unit: 'g', orderIndex: 3 },
        { name: 'bacon', quantity: '150', unit: 'g', orderIndex: 4 },
        { name: 'potato starch', quantity: '2', unit: 'tbsp', orderIndex: 5 },
        { name: 'salt', quantity: '1', unit: 'tbsp', orderIndex: 6 },
        { name: 'black pepper', quantity: '1', unit: 'tsp', orderIndex: 7 },
      ],
      steps: [
        { orderIndex: 0, text: 'Peel potatoes. Grate 2/3 raw and boil 1/3 until soft. Squeeze excess liquid from raw potatoes (save the starch that settles at the bottom). Mash boiled potatoes and combine with grated raw potatoes and starch.', duration: 1800, techniqueTag: 'prep' },
        { orderIndex: 1, text: 'Make filling: mix ground pork with finely diced onion, salt, and pepper.', duration: 300, techniqueTag: 'mix' },
        { orderIndex: 2, text: 'Take a handful of potato dough, flatten in your palm, place a spoonful of meat filling in the center. Shape into a large oval (zeppelin shape), sealing completely.', duration: 900, techniqueTag: 'shape' },
        { orderIndex: 3, text: 'Gently lower dumplings into a large pot of salted boiling water. Reduce to a gentle simmer. Cook 25-30 minutes. They will float when done.', duration: 1800, techniqueTag: 'boil' },
        { orderIndex: 4, text: 'While dumplings cook, dice and fry bacon until crispy. Serve dumplings with sour cream, crispy bacon bits, and the rendered bacon fat drizzled on top.', duration: 360, techniqueTag: 'fry' },
      ],
    },
    {
      name: 'Šaltibarščiai (Cold Beet Soup)',
      description: 'Vibrant pink Lithuanian cold soup made from kefir and beets. Refreshing summer classic served with hot boiled potatoes.',
      prepTime: 20,
      cookTime: 30,
      servings: 4,
      calories: 220,
      protein: 8,
      carbs: 28,
      fat: 9,
      difficulty: 'BEGINNER' as const,
      dietaryTags: ['vegetarian', 'gluten-free'],
      cuisineType: 'OTHER' as const,
      mealType: 'LUNCH' as const,
      imageStatus: 'COMPLETED' as const,
      scrapedFrom: 'curated',
      location: 'Vilnius',
      latitude: 54.6872,
      longitude: 25.2797,
      engagementLoves: 800,
      engagementBookmarks: 420,
      engagementViews: 5200,
      isViral: true,
      velocityScore: 65.0,
      ingredients: [
        { name: 'beets', quantity: '3', unit: 'medium', orderIndex: 0 },
        { name: 'kefir', quantity: '500', unit: 'ml', orderIndex: 1 },
        { name: 'cucumber', quantity: '1', unit: 'large', orderIndex: 2 },
        { name: 'eggs', quantity: '3', unit: 'hard-boiled', orderIndex: 3 },
        { name: 'dill', quantity: '1', unit: 'large bunch', orderIndex: 4 },
        { name: 'scallions', quantity: '4', unit: 'stalks', orderIndex: 5 },
        { name: 'potatoes', quantity: '4', unit: 'medium', orderIndex: 6 },
        { name: 'sour cream', quantity: '100', unit: 'g', orderIndex: 7 },
      ],
      steps: [
        { orderIndex: 0, text: 'Boil beets until tender (about 30 minutes). Cool, peel, and grate on a coarse grater. Save some beet cooking liquid.', duration: 2100, techniqueTag: 'boil' },
        { orderIndex: 1, text: 'Dice cucumber, slice scallions, chop dill, and dice hard-boiled eggs.', duration: 300, techniqueTag: 'prep' },
        { orderIndex: 2, text: 'Combine grated beets with kefir and enough beet liquid to reach desired consistency. Add cucumber, scallions, dill, and eggs. Season with salt.', duration: 180, techniqueTag: 'mix' },
        { orderIndex: 3, text: 'Refrigerate until very cold (at least 1 hour). Boil potatoes separately.', duration: 3600, techniqueTag: 'chill' },
        { orderIndex: 4, text: 'Serve soup cold in deep bowls with a dollop of sour cream and hot boiled potatoes on the side.', duration: 60, techniqueTag: 'serve' },
      ],
    },
  ];

  let recipeCount = 0;
  for (const { ingredients: recipeIngredients, steps: recipeSteps, ...recipeData } of recipes) {
    // Check if recipe already exists (by name + location for idempotent seeding)
    const existing = await prisma.recipe.findFirst({
      where: { name: recipeData.name, location: recipeData.location },
    });
    if (existing) continue;

    await prisma.recipe.create({
      data: {
        ...recipeData,
        ingredients: {
          create: recipeIngredients,
        },
        steps: {
          create: recipeSteps,
        },
      },
    });
    recipeCount++;
  }

  console.log(`✅ Seeded ${recipeCount} recipes (${recipes.length - recipeCount} already existed)`);
}
