import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Seeding ingredient catalog...');

  const ingredients = [
    // DAIRY (~20 entries)
    {
      canonicalName: 'eggs',
      canonicalNameTR: 'yumurta',
      aliases: ['egg', 'large eggs', 'whole eggs', 'yumurtalar'],
      defaultCategory: 'dairy',
      defaultShelfLifeDays: 30,
    },
    {
      canonicalName: 'milk',
      canonicalNameTR: 'süt',
      aliases: ['whole milk', '2% milk', 'skim milk', 'tam yağlı süt', 'yağsız süt'],
      defaultCategory: 'dairy',
      defaultShelfLifeDays: 7,
    },
    {
      canonicalName: 'butter',
      canonicalNameTR: 'tereyağı',
      aliases: ['unsalted butter', 'salted butter', 'tuzlu tereyağı', 'tuzsuz tereyağı'],
      defaultCategory: 'dairy',
      defaultShelfLifeDays: 60,
    },
    {
      canonicalName: 'cheese',
      canonicalNameTR: 'peynir',
      aliases: ['cheddar', 'mozzarella', 'parmesan', 'kaşar peyniri', 'tulum peyniri'],
      defaultCategory: 'dairy',
      defaultShelfLifeDays: 30,
    },
    {
      canonicalName: 'yogurt',
      canonicalNameTR: 'yoğurt',
      aliases: ['greek yogurt', 'plain yogurt', 'süzme yoğurt'],
      defaultCategory: 'dairy',
      defaultShelfLifeDays: 14,
    },
    {
      canonicalName: 'cream',
      canonicalNameTR: 'krema',
      aliases: ['heavy cream', 'whipping cream', 'çırpma kremasi'],
      defaultCategory: 'dairy',
      defaultShelfLifeDays: 7,
    },
    {
      canonicalName: 'sour cream',
      canonicalNameTR: 'ekşi krema',
      aliases: ['soured cream'],
      defaultCategory: 'dairy',
      defaultShelfLifeDays: 14,
    },
    {
      canonicalName: 'cream cheese',
      canonicalNameTR: 'krem peynir',
      aliases: ['philadelphia'],
      defaultCategory: 'dairy',
      defaultShelfLifeDays: 21,
    },
    {
      canonicalName: 'mozzarella',
      canonicalNameTR: 'mozzarella',
      aliases: ['fresh mozzarella', 'mozzarella peyniri'],
      defaultCategory: 'dairy',
      defaultShelfLifeDays: 14,
    },
    {
      canonicalName: 'parmesan',
      canonicalNameTR: 'parmesan',
      aliases: ['parmigiano reggiano', 'parmesan peyniri'],
      defaultCategory: 'dairy',
      defaultShelfLifeDays: 60,
    },
    {
      canonicalName: 'cheddar',
      canonicalNameTR: 'çedar',
      aliases: ['cheddar cheese', 'sharp cheddar', 'çedar peyniri'],
      defaultCategory: 'dairy',
      defaultShelfLifeDays: 30,
    },
    {
      canonicalName: 'feta',
      canonicalNameTR: 'beyaz peynir',
      aliases: ['feta cheese', 'beyaz peynir'],
      defaultCategory: 'dairy',
      defaultShelfLifeDays: 21,
    },
    {
      canonicalName: 'ricotta',
      canonicalNameTR: 'ricotta',
      aliases: ['ricotta cheese', 'ricotta peyniri'],
      defaultCategory: 'dairy',
      defaultShelfLifeDays: 7,
    },
    {
      canonicalName: 'cottage cheese',
      canonicalNameTR: 'lor peyniri',
      aliases: ['cottage', 'lor'],
      defaultCategory: 'dairy',
      defaultShelfLifeDays: 10,
    },
    {
      canonicalName: 'whipped cream',
      canonicalNameTR: 'çırpılmış krema',
      aliases: ['chantilly', 'şanti'],
      defaultCategory: 'dairy',
      defaultShelfLifeDays: 7,
    },
    {
      canonicalName: 'condensed milk',
      canonicalNameTR: 'yoğunlaştırılmış süt',
      aliases: ['sweetened condensed milk', 'koyulaştırılmış süt'],
      defaultCategory: 'dairy',
      defaultShelfLifeDays: 365,
    },
    {
      canonicalName: 'buttermilk',
      canonicalNameTR: 'ayran',
      aliases: ['cultured buttermilk'],
      defaultCategory: 'dairy',
      defaultShelfLifeDays: 14,
    },
    {
      canonicalName: 'ghee',
      canonicalNameTR: 'sade yağ',
      aliases: ['clarified butter', 'tereyağı'],
      defaultCategory: 'dairy',
      defaultShelfLifeDays: 90,
    },
    {
      canonicalName: 'heavy cream',
      canonicalNameTR: 'ağır krema',
      aliases: ['double cream', 'krem şanti'],
      defaultCategory: 'dairy',
      defaultShelfLifeDays: 7,
    },
    {
      canonicalName: 'goat cheese',
      canonicalNameTR: 'keçi peyniri',
      aliases: ['chevre', 'keçi peyniri'],
      defaultCategory: 'dairy',
      defaultShelfLifeDays: 14,
    },

    // PRODUCE (~40 entries)
    {
      canonicalName: 'tomatoes',
      canonicalNameTR: 'domates',
      aliases: ['tomato', 'cherry tomatoes', 'roma tomatoes', 'domates'],
      defaultCategory: 'produce',
      defaultShelfLifeDays: 7,
    },
    {
      canonicalName: 'onions',
      canonicalNameTR: 'soğan',
      aliases: ['onion', 'yellow onions', 'red onions', 'white onions', 'soğanlar'],
      defaultCategory: 'produce',
      defaultShelfLifeDays: 30,
    },
    {
      canonicalName: 'garlic',
      canonicalNameTR: 'sarımsak',
      aliases: ['garlic cloves', 'sarımsak dişi'],
      defaultCategory: 'produce',
      defaultShelfLifeDays: 60,
    },
    {
      canonicalName: 'potatoes',
      canonicalNameTR: 'patates',
      aliases: ['potato', 'russet potatoes', 'yukon gold', 'patatesi'],
      defaultCategory: 'produce',
      defaultShelfLifeDays: 30,
    },
    {
      canonicalName: 'carrots',
      canonicalNameTR: 'havuç',
      aliases: ['carrot', 'baby carrots', 'havuçlar'],
      defaultCategory: 'produce',
      defaultShelfLifeDays: 14,
    },
    {
      canonicalName: 'bell peppers',
      canonicalNameTR: 'biber',
      aliases: ['bell pepper', 'red pepper', 'green pepper', 'dolma biberı'],
      defaultCategory: 'produce',
      defaultShelfLifeDays: 10,
    },
    {
      canonicalName: 'cucumber',
      canonicalNameTR: 'salatalık',
      aliases: ['cucumbers', 'salatalıklar'],
      defaultCategory: 'produce',
      defaultShelfLifeDays: 7,
    },
    {
      canonicalName: 'lettuce',
      canonicalNameTR: 'marul',
      aliases: ['romaine', 'iceberg lettuce', 'green leaf', 'kıvırcık marul'],
      defaultCategory: 'produce',
      defaultShelfLifeDays: 7,
    },
    {
      canonicalName: 'spinach',
      canonicalNameTR: 'ıspanak',
      aliases: ['baby spinach', 'fresh spinach', 'ıspanak yaprakları'],
      defaultCategory: 'produce',
      defaultShelfLifeDays: 5,
    },
    {
      canonicalName: 'broccoli',
      canonicalNameTR: 'brokoli',
      aliases: ['broccoli florets', 'brokoliler'],
      defaultCategory: 'produce',
      defaultShelfLifeDays: 7,
    },
    {
      canonicalName: 'mushrooms',
      canonicalNameTR: 'mantar',
      aliases: ['button mushrooms', 'cremini', 'portobello', 'mantarlar'],
      defaultCategory: 'produce',
      defaultShelfLifeDays: 7,
    },
    {
      canonicalName: 'zucchini',
      canonicalNameTR: 'kabak',
      aliases: ['courgette', 'sakız kabağı'],
      defaultCategory: 'produce',
      defaultShelfLifeDays: 10,
    },
    {
      canonicalName: 'eggplant',
      canonicalNameTR: 'patlıcan',
      aliases: ['aubergine', 'patlıcanlar'],
      defaultCategory: 'produce',
      defaultShelfLifeDays: 10,
    },
    {
      canonicalName: 'corn',
      canonicalNameTR: 'mısır',
      aliases: ['sweet corn', 'corn on the cob', 'tatlı mısır'],
      defaultCategory: 'produce',
      defaultShelfLifeDays: 5,
    },
    {
      canonicalName: 'peas',
      canonicalNameTR: 'bezelye',
      aliases: ['green peas', 'fresh peas', 'taze bezelye'],
      defaultCategory: 'produce',
      defaultShelfLifeDays: 7,
    },
    {
      canonicalName: 'green beans',
      canonicalNameTR: 'taze fasulye',
      aliases: ['string beans', 'snap beans', 'çalı fasulyesi'],
      defaultCategory: 'produce',
      defaultShelfLifeDays: 7,
    },
    {
      canonicalName: 'celery',
      canonicalNameTR: 'kereviz',
      aliases: ['celery stalks', 'kereviz sapı'],
      defaultCategory: 'produce',
      defaultShelfLifeDays: 14,
    },
    {
      canonicalName: 'avocado',
      canonicalNameTR: 'avokado',
      aliases: ['avocados', 'hass avocado', 'avokadolar'],
      defaultCategory: 'produce',
      defaultShelfLifeDays: 5,
    },
    {
      canonicalName: 'lemon',
      canonicalNameTR: 'limon',
      aliases: ['lemons', 'fresh lemon', 'limonlar'],
      defaultCategory: 'produce',
      defaultShelfLifeDays: 14,
    },
    {
      canonicalName: 'lime',
      canonicalNameTR: 'misket limonu',
      aliases: ['limes', 'key lime', 'misket limonları'],
      defaultCategory: 'produce',
      defaultShelfLifeDays: 14,
    },
    {
      canonicalName: 'oranges',
      canonicalNameTR: 'portakal',
      aliases: ['orange', 'navel oranges', 'blood orange', 'portalaklar'],
      defaultCategory: 'produce',
      defaultShelfLifeDays: 14,
    },
    {
      canonicalName: 'apples',
      canonicalNameTR: 'elma',
      aliases: ['apple', 'granny smith', 'honeycrisp', 'elmalar'],
      defaultCategory: 'produce',
      defaultShelfLifeDays: 30,
    },
    {
      canonicalName: 'bananas',
      canonicalNameTR: 'muz',
      aliases: ['banana', 'muzlar'],
      defaultCategory: 'produce',
      defaultShelfLifeDays: 5,
    },
    {
      canonicalName: 'strawberries',
      canonicalNameTR: 'çilek',
      aliases: ['strawberry', 'fresh strawberries', 'çilekler'],
      defaultCategory: 'produce',
      defaultShelfLifeDays: 5,
    },
    {
      canonicalName: 'blueberries',
      canonicalNameTR: 'yaban mersini',
      aliases: ['blueberry', 'fresh blueberries', 'maviyemiş'],
      defaultCategory: 'produce',
      defaultShelfLifeDays: 7,
    },
    {
      canonicalName: 'grapes',
      canonicalNameTR: 'üzüm',
      aliases: ['green grapes', 'red grapes', 'üzümler'],
      defaultCategory: 'produce',
      defaultShelfLifeDays: 7,
    },
    {
      canonicalName: 'watermelon',
      canonicalNameTR: 'karpuz',
      aliases: ['seedless watermelon', 'karpuzlar'],
      defaultCategory: 'produce',
      defaultShelfLifeDays: 14,
    },
    {
      canonicalName: 'melon',
      canonicalNameTR: 'kavun',
      aliases: ['cantaloupe', 'honeydew', 'kavunlar'],
      defaultCategory: 'produce',
      defaultShelfLifeDays: 7,
    },
    {
      canonicalName: 'pineapple',
      canonicalNameTR: 'ananas',
      aliases: ['fresh pineapple', 'ananaslar'],
      defaultCategory: 'produce',
      defaultShelfLifeDays: 5,
    },
    {
      canonicalName: 'mango',
      canonicalNameTR: 'mango',
      aliases: ['mangoes', 'fresh mango', 'mangolar'],
      defaultCategory: 'produce',
      defaultShelfLifeDays: 7,
    },
    {
      canonicalName: 'ginger',
      canonicalNameTR: 'zencefil',
      aliases: ['fresh ginger', 'ginger root', 'zencefil kökü'],
      defaultCategory: 'produce',
      defaultShelfLifeDays: 21,
    },
    {
      canonicalName: 'parsley',
      canonicalNameTR: 'maydanoz',
      aliases: ['fresh parsley', 'flat leaf parsley', 'taze maydanoz'],
      defaultCategory: 'produce',
      defaultShelfLifeDays: 7,
    },
    {
      canonicalName: 'cilantro',
      canonicalNameTR: 'kişniş',
      aliases: ['coriander leaves', 'fresh cilantro', 'kişniş yaprağı'],
      defaultCategory: 'produce',
      defaultShelfLifeDays: 7,
    },
    {
      canonicalName: 'mint',
      canonicalNameTR: 'nane',
      aliases: ['fresh mint', 'spearmint', 'taze nane'],
      defaultCategory: 'produce',
      defaultShelfLifeDays: 7,
    },
    {
      canonicalName: 'dill',
      canonicalNameTR: 'dereotu',
      aliases: ['fresh dill', 'dill weed', 'taze dereotu'],
      defaultCategory: 'produce',
      defaultShelfLifeDays: 7,
    },
    {
      canonicalName: 'basil',
      canonicalNameTR: 'fesleğen',
      aliases: ['fresh basil', 'sweet basil', 'taze fesleğen'],
      defaultCategory: 'produce',
      defaultShelfLifeDays: 5,
    },
    {
      canonicalName: 'rosemary',
      canonicalNameTR: 'biberiye',
      aliases: ['fresh rosemary', 'taze biberiye'],
      defaultCategory: 'produce',
      defaultShelfLifeDays: 14,
    },
    {
      canonicalName: 'thyme',
      canonicalNameTR: 'kekik',
      aliases: ['fresh thyme', 'taze kekik'],
      defaultCategory: 'produce',
      defaultShelfLifeDays: 14,
    },
    {
      canonicalName: 'chives',
      canonicalNameTR: 'frenk soğanı',
      aliases: ['fresh chives', 'taze frenk soğanı'],
      defaultCategory: 'produce',
      defaultShelfLifeDays: 7,
    },
    {
      canonicalName: 'scallions',
      canonicalNameTR: 'yeşil soğan',
      aliases: ['green onions', 'spring onions', 'taze soğan'],
      defaultCategory: 'produce',
      defaultShelfLifeDays: 7,
    },

    // MEAT (~15 entries)
    {
      canonicalName: 'chicken breast',
      canonicalNameTR: 'tavuk göğsü',
      aliases: ['chicken breasts', 'boneless chicken breast', 'tavuk fileto'],
      defaultCategory: 'meat',
      defaultShelfLifeDays: 2,
    },
    {
      canonicalName: 'chicken thighs',
      canonicalNameTR: 'tavuk butu',
      aliases: ['chicken thigh', 'boneless chicken thighs', 'tavuk uyluk'],
      defaultCategory: 'meat',
      defaultShelfLifeDays: 2,
    },
    {
      canonicalName: 'ground beef',
      canonicalNameTR: 'kıyma',
      aliases: ['beef mince', 'minced beef', 'dana kıyma'],
      defaultCategory: 'meat',
      defaultShelfLifeDays: 2,
    },
    {
      canonicalName: 'beef steak',
      canonicalNameTR: 'biftek',
      aliases: ['ribeye', 'sirloin', 'strip steak', 'dana biftek'],
      defaultCategory: 'meat',
      defaultShelfLifeDays: 3,
    },
    {
      canonicalName: 'lamb',
      canonicalNameTR: 'kuzu',
      aliases: ['lamb chops', 'lamb shoulder', 'kuzu eti'],
      defaultCategory: 'meat',
      defaultShelfLifeDays: 3,
    },
    {
      canonicalName: 'pork chop',
      canonicalNameTR: 'domuz pirzolası',
      aliases: ['pork chops', 'bone-in pork chops'],
      defaultCategory: 'meat',
      defaultShelfLifeDays: 3,
    },
    {
      canonicalName: 'bacon',
      canonicalNameTR: 'pastırma',
      aliases: ['turkey bacon', 'pork bacon', 'bacon strips'],
      defaultCategory: 'meat',
      defaultShelfLifeDays: 7,
    },
    {
      canonicalName: 'sausage',
      canonicalNameTR: 'sosis',
      aliases: ['italian sausage', 'breakfast sausage', 'sucuk'],
      defaultCategory: 'meat',
      defaultShelfLifeDays: 5,
    },
    {
      canonicalName: 'turkey',
      canonicalNameTR: 'hindi',
      aliases: ['turkey breast', 'ground turkey', 'hindi göğsü'],
      defaultCategory: 'meat',
      defaultShelfLifeDays: 2,
    },
    {
      canonicalName: 'ham',
      canonicalNameTR: 'jambon',
      aliases: ['deli ham', 'smoked ham', 'jambonlar'],
      defaultCategory: 'meat',
      defaultShelfLifeDays: 7,
    },
    {
      canonicalName: 'salami',
      canonicalNameTR: 'salam',
      aliases: ['genoa salami', 'hard salami', 'salamlar'],
      defaultCategory: 'meat',
      defaultShelfLifeDays: 21,
    },
    {
      canonicalName: 'ground turkey',
      canonicalNameTR: 'hindi kıyma',
      aliases: ['turkey mince', 'minced turkey'],
      defaultCategory: 'meat',
      defaultShelfLifeDays: 2,
    },
    {
      canonicalName: 'veal',
      canonicalNameTR: 'dana eti',
      aliases: ['veal cutlet', 'veal scaloppine', 'dana bonfile'],
      defaultCategory: 'meat',
      defaultShelfLifeDays: 3,
    },
    {
      canonicalName: 'liver',
      canonicalNameTR: 'ciğer',
      aliases: ['chicken liver', 'beef liver', 'tavuk ciğeri'],
      defaultCategory: 'meat',
      defaultShelfLifeDays: 2,
    },
    {
      canonicalName: 'meatballs',
      canonicalNameTR: 'köfte',
      aliases: ['beef meatballs', 'turkish meatballs', 'izgara köfte'],
      defaultCategory: 'meat',
      defaultShelfLifeDays: 2,
    },

    // SEAFOOD (~10 entries)
    {
      canonicalName: 'salmon',
      canonicalNameTR: 'somon',
      aliases: ['salmon fillet', 'atlantic salmon', 'somon fileto'],
      defaultCategory: 'seafood',
      defaultShelfLifeDays: 2,
    },
    {
      canonicalName: 'shrimp',
      canonicalNameTR: 'karides',
      aliases: ['prawns', 'jumbo shrimp', 'karides kuyrukları'],
      defaultCategory: 'seafood',
      defaultShelfLifeDays: 2,
    },
    {
      canonicalName: 'tuna',
      canonicalNameTR: 'ton balığı',
      aliases: ['tuna steak', 'yellowfin tuna', 'ton balığı konservesi'],
      defaultCategory: 'seafood',
      defaultShelfLifeDays: 2,
    },
    {
      canonicalName: 'cod',
      canonicalNameTR: 'morina',
      aliases: ['cod fillet', 'atlantic cod', 'morina balığı'],
      defaultCategory: 'seafood',
      defaultShelfLifeDays: 2,
    },
    {
      canonicalName: 'sea bass',
      canonicalNameTR: 'levrek',
      aliases: ['branzino', 'european sea bass', 'levrek balığı'],
      defaultCategory: 'seafood',
      defaultShelfLifeDays: 2,
    },
    {
      canonicalName: 'mussels',
      canonicalNameTR: 'midye',
      aliases: ['fresh mussels', 'blue mussels', 'midyeler'],
      defaultCategory: 'seafood',
      defaultShelfLifeDays: 1,
    },
    {
      canonicalName: 'squid',
      canonicalNameTR: 'kalamar',
      aliases: ['calamari', 'fresh squid', 'kalamar halkaları'],
      defaultCategory: 'seafood',
      defaultShelfLifeDays: 2,
    },
    {
      canonicalName: 'anchovies',
      canonicalNameTR: 'hamsi',
      aliases: ['fresh anchovies', 'anchovy fillets', 'taze hamsi'],
      defaultCategory: 'seafood',
      defaultShelfLifeDays: 1,
    },
    {
      canonicalName: 'mackerel',
      canonicalNameTR: 'uskumru',
      aliases: ['spanish mackerel', 'atlantic mackerel', 'taze uskumru'],
      defaultCategory: 'seafood',
      defaultShelfLifeDays: 2,
    },
    {
      canonicalName: 'trout',
      canonicalNameTR: 'alabalık',
      aliases: ['rainbow trout', 'trout fillet', 'alabalık fileto'],
      defaultCategory: 'seafood',
      defaultShelfLifeDays: 2,
    },

    // GRAINS (~20 entries)
    {
      canonicalName: 'rice',
      canonicalNameTR: 'pirinç',
      aliases: ['white rice', 'basmati rice', 'jasmine rice', 'beyaz pirinç'],
      defaultCategory: 'grains',
      defaultShelfLifeDays: 365,
    },
    {
      canonicalName: 'pasta',
      canonicalNameTR: 'makarna',
      aliases: ['spaghetti', 'penne', 'fettuccine', 'spagetti'],
      defaultCategory: 'grains',
      defaultShelfLifeDays: 365,
    },
    {
      canonicalName: 'bread',
      canonicalNameTR: 'ekmek',
      aliases: ['loaf bread', 'white bread', 'whole wheat bread', 'tam buğday ekmeği'],
      defaultCategory: 'grains',
      defaultShelfLifeDays: 5,
    },
    {
      canonicalName: 'flour',
      canonicalNameTR: 'un',
      aliases: ['all-purpose flour', 'bread flour', 'cake flour', 'buğday unu'],
      defaultCategory: 'grains',
      defaultShelfLifeDays: 365,
    },
    {
      canonicalName: 'oats',
      canonicalNameTR: 'yulaf',
      aliases: ['rolled oats', 'old fashioned oats', 'quick oats', 'yulaf ezmesi'],
      defaultCategory: 'grains',
      defaultShelfLifeDays: 365,
    },
    {
      canonicalName: 'quinoa',
      canonicalNameTR: 'kinoa',
      aliases: ['white quinoa', 'red quinoa', 'tricolor quinoa'],
      defaultCategory: 'grains',
      defaultShelfLifeDays: 365,
    },
    {
      canonicalName: 'couscous',
      canonicalNameTR: 'kuskus',
      aliases: ['moroccan couscous', 'israeli couscous'],
      defaultCategory: 'grains',
      defaultShelfLifeDays: 365,
    },
    {
      canonicalName: 'bulgur',
      canonicalNameTR: 'bulgur',
      aliases: ['fine bulgur', 'coarse bulgur', 'köftelik bulgur'],
      defaultCategory: 'grains',
      defaultShelfLifeDays: 365,
    },
    {
      canonicalName: 'noodles',
      canonicalNameTR: 'erişte',
      aliases: ['egg noodles', 'rice noodles', 'udon noodles', 'şehriye'],
      defaultCategory: 'grains',
      defaultShelfLifeDays: 365,
    },
    {
      canonicalName: 'tortillas',
      canonicalNameTR: 'tortilla',
      aliases: ['flour tortillas', 'corn tortillas', 'wrap'],
      defaultCategory: 'grains',
      defaultShelfLifeDays: 14,
    },
    {
      canonicalName: 'pita',
      canonicalNameTR: 'pide',
      aliases: ['pita bread', 'pide ekmeği'],
      defaultCategory: 'grains',
      defaultShelfLifeDays: 7,
    },
    {
      canonicalName: 'cornmeal',
      canonicalNameTR: 'mısır unu',
      aliases: ['polenta', 'corn flour', 'mısır irmiği'],
      defaultCategory: 'grains',
      defaultShelfLifeDays: 365,
    },
    {
      canonicalName: 'semolina',
      canonicalNameTR: 'irmik',
      aliases: ['semolina flour', 'ince irmik'],
      defaultCategory: 'grains',
      defaultShelfLifeDays: 365,
    },
    {
      canonicalName: 'barley',
      canonicalNameTR: 'arpa',
      aliases: ['pearl barley', 'hulled barley', 'arpa taneleri'],
      defaultCategory: 'grains',
      defaultShelfLifeDays: 365,
    },
    {
      canonicalName: 'rye',
      canonicalNameTR: 'çavdar',
      aliases: ['rye flour', 'rye bread', 'çavdar unu'],
      defaultCategory: 'grains',
      defaultShelfLifeDays: 365,
    },
    {
      canonicalName: 'breadcrumbs',
      canonicalNameTR: 'galeta unu',
      aliases: ['panko', 'italian breadcrumbs', 'ekmek kırıntısı'],
      defaultCategory: 'grains',
      defaultShelfLifeDays: 180,
    },
    {
      canonicalName: 'crackers',
      canonicalNameTR: 'tuzlu kraker',
      aliases: ['saltine crackers', 'water crackers', 'krakerler'],
      defaultCategory: 'grains',
      defaultShelfLifeDays: 180,
    },
    {
      canonicalName: 'cereal',
      canonicalNameTR: 'tahıl gevreği',
      aliases: ['breakfast cereal', 'corn flakes', 'mısır gevreği'],
      defaultCategory: 'grains',
      defaultShelfLifeDays: 180,
    },
    {
      canonicalName: 'granola',
      canonicalNameTR: 'granola',
      aliases: ['granola clusters', 'granola cereal'],
      defaultCategory: 'grains',
      defaultShelfLifeDays: 180,
    },
    {
      canonicalName: 'pizza dough',
      canonicalNameTR: 'pizza hamuru',
      aliases: ['fresh pizza dough', 'pizza hamurunuz'],
      defaultCategory: 'grains',
      defaultShelfLifeDays: 7,
    },

    // BAKING (~15 entries)
    {
      canonicalName: 'sugar',
      canonicalNameTR: 'şeker',
      aliases: ['white sugar', 'granulated sugar', 'toz şeker'],
      defaultCategory: 'baking',
      defaultShelfLifeDays: 730,
    },
    {
      canonicalName: 'brown sugar',
      canonicalNameTR: 'esmer şeker',
      aliases: ['light brown sugar', 'dark brown sugar'],
      defaultCategory: 'baking',
      defaultShelfLifeDays: 730,
    },
    {
      canonicalName: 'powdered sugar',
      canonicalNameTR: 'pudra şekeri',
      aliases: ['icing sugar', 'confectioners sugar'],
      defaultCategory: 'baking',
      defaultShelfLifeDays: 730,
    },
    {
      canonicalName: 'baking powder',
      canonicalNameTR: 'kabartma tozu',
      aliases: ['double acting baking powder'],
      defaultCategory: 'baking',
      defaultShelfLifeDays: 365,
    },
    {
      canonicalName: 'baking soda',
      canonicalNameTR: 'karbonat',
      aliases: ['sodium bicarbonate', 'bicarbonate of soda'],
      defaultCategory: 'baking',
      defaultShelfLifeDays: 730,
    },
    {
      canonicalName: 'vanilla extract',
      canonicalNameTR: 'vanilya özütü',
      aliases: ['pure vanilla', 'vanilya aroması'],
      defaultCategory: 'baking',
      defaultShelfLifeDays: 1825,
    },
    {
      canonicalName: 'cocoa powder',
      canonicalNameTR: 'kakao',
      aliases: ['unsweetened cocoa', 'dutch cocoa', 'kakao tozu'],
      defaultCategory: 'baking',
      defaultShelfLifeDays: 730,
    },
    {
      canonicalName: 'chocolate',
      canonicalNameTR: 'çikolata',
      aliases: ['dark chocolate', 'milk chocolate', 'bitter çikolata'],
      defaultCategory: 'baking',
      defaultShelfLifeDays: 365,
    },
    {
      canonicalName: 'honey',
      canonicalNameTR: 'bal',
      aliases: ['raw honey', 'organic honey', 'çiçek balı'],
      defaultCategory: 'baking',
      defaultShelfLifeDays: 1825,
    },
    {
      canonicalName: 'maple syrup',
      canonicalNameTR: 'akça ağaç şurubu',
      aliases: ['pure maple syrup', 'grade a maple syrup'],
      defaultCategory: 'baking',
      defaultShelfLifeDays: 365,
    },
    {
      canonicalName: 'molasses',
      canonicalNameTR: 'pekmez',
      aliases: ['blackstrap molasses', 'üzüm pekmezi'],
      defaultCategory: 'baking',
      defaultShelfLifeDays: 730,
    },
    {
      canonicalName: 'cornstarch',
      canonicalNameTR: 'nişasta',
      aliases: ['corn flour', 'mısır nişastası'],
      defaultCategory: 'baking',
      defaultShelfLifeDays: 730,
    },
    {
      canonicalName: 'yeast',
      canonicalNameTR: 'maya',
      aliases: ['active dry yeast', 'instant yeast', 'kuru maya'],
      defaultCategory: 'baking',
      defaultShelfLifeDays: 365,
    },
    {
      canonicalName: 'gelatin',
      canonicalNameTR: 'jelatin',
      aliases: ['unflavored gelatin', 'gelatin powder'],
      defaultCategory: 'baking',
      defaultShelfLifeDays: 730,
    },
    {
      canonicalName: 'food coloring',
      canonicalNameTR: 'gıda boyası',
      aliases: ['gel food coloring', 'liquid food color'],
      defaultCategory: 'baking',
      defaultShelfLifeDays: 730,
    },

    // SPICES (~25 entries)
    {
      canonicalName: 'salt',
      canonicalNameTR: 'tuz',
      aliases: ['sea salt', 'kosher salt', 'table salt', 'deniz tuzu'],
      defaultCategory: 'spices',
      defaultShelfLifeDays: 1825,
    },
    {
      canonicalName: 'black pepper',
      canonicalNameTR: 'karabiber',
      aliases: ['ground black pepper', 'peppercorns', 'karabiber taneleri'],
      defaultCategory: 'spices',
      defaultShelfLifeDays: 730,
    },
    {
      canonicalName: 'red pepper flakes',
      canonicalNameTR: 'pul biber',
      aliases: ['crushed red pepper', 'red chili flakes', 'aleppo pepper'],
      defaultCategory: 'spices',
      defaultShelfLifeDays: 730,
    },
    {
      canonicalName: 'cumin',
      canonicalNameTR: 'kimyon',
      aliases: ['ground cumin', 'cumin seeds', 'kimyon tohumu'],
      defaultCategory: 'spices',
      defaultShelfLifeDays: 730,
    },
    {
      canonicalName: 'paprika',
      canonicalNameTR: 'tatlı toz biber',
      aliases: ['sweet paprika', 'smoked paprika', 'közlenmiş biber tozu'],
      defaultCategory: 'spices',
      defaultShelfLifeDays: 730,
    },
    {
      canonicalName: 'turmeric',
      canonicalNameTR: 'zerdeçal',
      aliases: ['ground turmeric', 'turmeric powder', 'hint safranı'],
      defaultCategory: 'spices',
      defaultShelfLifeDays: 730,
    },
    {
      canonicalName: 'cinnamon',
      canonicalNameTR: 'tarçın',
      aliases: ['ground cinnamon', 'cinnamon sticks', 'tarçın çubuğu'],
      defaultCategory: 'spices',
      defaultShelfLifeDays: 730,
    },
    {
      canonicalName: 'oregano',
      canonicalNameTR: 'kekik',
      aliases: ['dried oregano', 'greek oregano', 'kurutulmuş kekik'],
      defaultCategory: 'spices',
      defaultShelfLifeDays: 730,
    },
    {
      canonicalName: 'bay leaf',
      canonicalNameTR: 'defne yaprağı',
      aliases: ['bay leaves', 'dried bay leaves', 'defne yaprakları'],
      defaultCategory: 'spices',
      defaultShelfLifeDays: 730,
    },
    {
      canonicalName: 'nutmeg',
      canonicalNameTR: 'muskat',
      aliases: ['ground nutmeg', 'whole nutmeg', 'hindistan cevizi'],
      defaultCategory: 'spices',
      defaultShelfLifeDays: 730,
    },
    {
      canonicalName: 'cloves',
      canonicalNameTR: 'karanfil',
      aliases: ['whole cloves', 'ground cloves', 'karanfil taneleri'],
      defaultCategory: 'spices',
      defaultShelfLifeDays: 730,
    },
    {
      canonicalName: 'cardamom',
      canonicalNameTR: 'kakule',
      aliases: ['green cardamom', 'cardamom pods', 'kakule taneleri'],
      defaultCategory: 'spices',
      defaultShelfLifeDays: 730,
    },
    {
      canonicalName: 'coriander',
      canonicalNameTR: 'kişniş',
      aliases: ['ground coriander', 'coriander seeds', 'kişniş tohumu'],
      defaultCategory: 'spices',
      defaultShelfLifeDays: 730,
    },
    {
      canonicalName: 'chili powder',
      canonicalNameTR: 'acı biber tozu',
      aliases: ['red chili powder', 'cayenne pepper', 'kırmızı biber tozu'],
      defaultCategory: 'spices',
      defaultShelfLifeDays: 730,
    },
    {
      canonicalName: 'cayenne',
      canonicalNameTR: 'kırmızı biber',
      aliases: ['cayenne pepper', 'ground cayenne'],
      defaultCategory: 'spices',
      defaultShelfLifeDays: 730,
    },
    {
      canonicalName: 'sumac',
      canonicalNameTR: 'sumak',
      aliases: ['ground sumac', 'sumac powder', 'sumak tozu'],
      defaultCategory: 'spices',
      defaultShelfLifeDays: 730,
    },
    {
      canonicalName: 'allspice',
      canonicalNameTR: 'yeni bahar',
      aliases: ['ground allspice', 'whole allspice'],
      defaultCategory: 'spices',
      defaultShelfLifeDays: 730,
    },
    {
      canonicalName: 'saffron',
      canonicalNameTR: 'safran',
      aliases: ['saffron threads', 'spanish saffron', 'safran iplikleri'],
      defaultCategory: 'spices',
      defaultShelfLifeDays: 1825,
    },
    {
      canonicalName: 'fennel seeds',
      canonicalNameTR: 'rezene',
      aliases: ['fennel', 'fennel seed', 'rezene tohumu'],
      defaultCategory: 'spices',
      defaultShelfLifeDays: 730,
    },
    {
      canonicalName: 'star anise',
      canonicalNameTR: 'yıldız anason',
      aliases: ['whole star anise', 'anise star'],
      defaultCategory: 'spices',
      defaultShelfLifeDays: 730,
    },
    {
      canonicalName: 'white pepper',
      canonicalNameTR: 'beyaz biber',
      aliases: ['ground white pepper', 'white peppercorns'],
      defaultCategory: 'spices',
      defaultShelfLifeDays: 730,
    },
    {
      canonicalName: 'curry powder',
      canonicalNameTR: 'köri',
      aliases: ['mild curry powder', 'hot curry powder', 'köri tozu'],
      defaultCategory: 'spices',
      defaultShelfLifeDays: 730,
    },
    {
      canonicalName: 'mustard seeds',
      canonicalNameTR: 'hardal tohumu',
      aliases: ['yellow mustard seeds', 'black mustard seeds'],
      defaultCategory: 'spices',
      defaultShelfLifeDays: 730,
    },
    {
      canonicalName: 'za\'atar',
      canonicalNameTR: 'zahter',
      aliases: ['zaatar', 'middle eastern spice blend'],
      defaultCategory: 'spices',
      defaultShelfLifeDays: 730,
    },
    {
      canonicalName: 'harissa',
      canonicalNameTR: 'harissa',
      aliases: ['harissa paste', 'north african spice paste'],
      defaultCategory: 'spices',
      defaultShelfLifeDays: 90,
    },

    // BEVERAGES (~10 entries)
    {
      canonicalName: 'water',
      canonicalNameTR: 'su',
      aliases: ['bottled water', 'mineral water', 'maden suyu'],
      defaultCategory: 'beverages',
      defaultShelfLifeDays: 365,
    },
    {
      canonicalName: 'coffee',
      canonicalNameTR: 'kahve',
      aliases: ['ground coffee', 'coffee beans', 'kahve çekirdekleri'],
      defaultCategory: 'beverages',
      defaultShelfLifeDays: 180,
    },
    {
      canonicalName: 'tea',
      canonicalNameTR: 'çay',
      aliases: ['black tea', 'green tea', 'siyah çay', 'yeşil çay'],
      defaultCategory: 'beverages',
      defaultShelfLifeDays: 730,
    },
    {
      canonicalName: 'orange juice',
      canonicalNameTR: 'portakal suyu',
      aliases: ['fresh orange juice', 'oj', 'taze portakal suyu'],
      defaultCategory: 'beverages',
      defaultShelfLifeDays: 7,
    },
    {
      canonicalName: 'apple juice',
      canonicalNameTR: 'elma suyu',
      aliases: ['fresh apple juice', 'taze elma suyu'],
      defaultCategory: 'beverages',
      defaultShelfLifeDays: 7,
    },
    {
      canonicalName: 'coconut milk',
      canonicalNameTR: 'hindistan cevizi sütü',
      aliases: ['canned coconut milk', 'coconut cream'],
      defaultCategory: 'beverages',
      defaultShelfLifeDays: 365,
    },
    {
      canonicalName: 'almond milk',
      canonicalNameTR: 'badem sütü',
      aliases: ['unsweetened almond milk', 'vanilla almond milk'],
      defaultCategory: 'beverages',
      defaultShelfLifeDays: 7,
    },
    {
      canonicalName: 'beer',
      canonicalNameTR: 'bira',
      aliases: ['lager', 'ale', 'craft beer', 'biralar'],
      defaultCategory: 'beverages',
      defaultShelfLifeDays: 180,
    },
    {
      canonicalName: 'wine',
      canonicalNameTR: 'şarap',
      aliases: ['red wine', 'white wine', 'kırmızı şarap', 'beyaz şarap'],
      defaultCategory: 'beverages',
      defaultShelfLifeDays: 1825,
    },
    {
      canonicalName: 'lemonade',
      canonicalNameTR: 'limonata',
      aliases: ['fresh lemonade', 'homemade lemonade'],
      defaultCategory: 'beverages',
      defaultShelfLifeDays: 5,
    },

    // SNACKS (~10 entries)
    {
      canonicalName: 'chips',
      canonicalNameTR: 'cips',
      aliases: ['potato chips', 'tortilla chips', 'patates cipsi'],
      defaultCategory: 'snacks',
      defaultShelfLifeDays: 180,
    },
    {
      canonicalName: 'nuts',
      canonicalNameTR: 'kuruyemiş',
      aliases: ['mixed nuts', 'roasted nuts', 'karışık kuruyemiş'],
      defaultCategory: 'snacks',
      defaultShelfLifeDays: 180,
    },
    {
      canonicalName: 'almonds',
      canonicalNameTR: 'badem',
      aliases: ['raw almonds', 'roasted almonds', 'bademler'],
      defaultCategory: 'snacks',
      defaultShelfLifeDays: 180,
    },
    {
      canonicalName: 'walnuts',
      canonicalNameTR: 'ceviz',
      aliases: ['walnut halves', 'cevizler'],
      defaultCategory: 'snacks',
      defaultShelfLifeDays: 180,
    },
    {
      canonicalName: 'peanuts',
      canonicalNameTR: 'yer fıstığı',
      aliases: ['roasted peanuts', 'salted peanuts', 'yer fıstıkları'],
      defaultCategory: 'snacks',
      defaultShelfLifeDays: 180,
    },
    {
      canonicalName: 'pistachios',
      canonicalNameTR: 'antep fıstığı',
      aliases: ['roasted pistachios', 'shelled pistachios', 'kabuklu fıstık'],
      defaultCategory: 'snacks',
      defaultShelfLifeDays: 180,
    },
    {
      canonicalName: 'hazelnuts',
      canonicalNameTR: 'fındık',
      aliases: ['roasted hazelnuts', 'fındıklar'],
      defaultCategory: 'snacks',
      defaultShelfLifeDays: 180,
    },
    {
      canonicalName: 'dried fruits',
      canonicalNameTR: 'kuru meyve',
      aliases: ['dried apricots', 'raisins', 'kuru kayısı', 'kuru üzüm'],
      defaultCategory: 'snacks',
      defaultShelfLifeDays: 180,
    },
    {
      canonicalName: 'popcorn',
      canonicalNameTR: 'mısır patlaği',
      aliases: ['microwave popcorn', 'popping corn', 'patlamış mısır'],
      defaultCategory: 'snacks',
      defaultShelfLifeDays: 180,
    },
    {
      canonicalName: 'trail mix',
      canonicalNameTR: 'karışık atıştırmalık',
      aliases: ['mixed snacks', 'nut and seed mix'],
      defaultCategory: 'snacks',
      defaultShelfLifeDays: 180,
    },

    // CONDIMENTS (~20 entries)
    {
      canonicalName: 'olive oil',
      canonicalNameTR: 'zeytinyağı',
      aliases: ['extra virgin olive oil', 'evoo', 'sızma zeytinyağı'],
      defaultCategory: 'condiments',
      defaultShelfLifeDays: 730,
    },
    {
      canonicalName: 'vegetable oil',
      canonicalNameTR: 'sıvı yağ',
      aliases: ['canola oil', 'sunflower oil', 'ayçiçek yağı'],
      defaultCategory: 'condiments',
      defaultShelfLifeDays: 730,
    },
    {
      canonicalName: 'soy sauce',
      canonicalNameTR: 'soya sosu',
      aliases: ['light soy sauce', 'dark soy sauce', 'tamari'],
      defaultCategory: 'condiments',
      defaultShelfLifeDays: 730,
    },
    {
      canonicalName: 'vinegar',
      canonicalNameTR: 'sirke',
      aliases: ['white vinegar', 'apple cider vinegar', 'elma sirkesi'],
      defaultCategory: 'condiments',
      defaultShelfLifeDays: 1825,
    },
    {
      canonicalName: 'ketchup',
      canonicalNameTR: 'ketçap',
      aliases: ['tomato ketchup', 'domates ketçabı'],
      defaultCategory: 'condiments',
      defaultShelfLifeDays: 365,
    },
    {
      canonicalName: 'mustard',
      canonicalNameTR: 'hardal',
      aliases: ['dijon mustard', 'yellow mustard', 'whole grain mustard'],
      defaultCategory: 'condiments',
      defaultShelfLifeDays: 365,
    },
    {
      canonicalName: 'mayonnaise',
      canonicalNameTR: 'mayanez',
      aliases: ['mayo', 'light mayo', 'hellmans'],
      defaultCategory: 'condiments',
      defaultShelfLifeDays: 60,
    },
    {
      canonicalName: 'hot sauce',
      canonicalNameTR: 'acı sos',
      aliases: ['tabasco', 'sriracha', 'hot pepper sauce'],
      defaultCategory: 'condiments',
      defaultShelfLifeDays: 365,
    },
    {
      canonicalName: 'worcestershire sauce',
      canonicalNameTR: 'worcestershire sos',
      aliases: ['worcestershire', 'lea & perrins'],
      defaultCategory: 'condiments',
      defaultShelfLifeDays: 730,
    },
    {
      canonicalName: 'tahini',
      canonicalNameTR: 'tahin',
      aliases: ['sesame paste', 'tahini paste', 'susam ezmesi'],
      defaultCategory: 'condiments',
      defaultShelfLifeDays: 180,
    },
    {
      canonicalName: 'tomato paste',
      canonicalNameTR: 'salça',
      aliases: ['tomato concentrate', 'domates salçası'],
      defaultCategory: 'condiments',
      defaultShelfLifeDays: 365,
    },
    {
      canonicalName: 'fish sauce',
      canonicalNameTR: 'balık sosu',
      aliases: ['nam pla', 'nuoc mam'],
      defaultCategory: 'condiments',
      defaultShelfLifeDays: 730,
    },
    {
      canonicalName: 'sesame oil',
      canonicalNameTR: 'susam yağı',
      aliases: ['toasted sesame oil', 'asian sesame oil'],
      defaultCategory: 'condiments',
      defaultShelfLifeDays: 365,
    },
    {
      canonicalName: 'coconut oil',
      canonicalNameTR: 'hindistan cevizi yağı',
      aliases: ['virgin coconut oil', 'organic coconut oil'],
      defaultCategory: 'condiments',
      defaultShelfLifeDays: 730,
    },
    {
      canonicalName: 'balsamic vinegar',
      canonicalNameTR: 'balzamik sirke',
      aliases: ['balsamic reduction', 'aged balsamic'],
      defaultCategory: 'condiments',
      defaultShelfLifeDays: 1825,
    },
    {
      canonicalName: 'rice vinegar',
      canonicalNameTR: 'pirinç sirkesi',
      aliases: ['rice wine vinegar', 'seasoned rice vinegar'],
      defaultCategory: 'condiments',
      defaultShelfLifeDays: 730,
    },
    {
      canonicalName: 'oyster sauce',
      canonicalNameTR: 'istiridye sosu',
      aliases: ['lee kum kee oyster sauce'],
      defaultCategory: 'condiments',
      defaultShelfLifeDays: 365,
    },
    {
      canonicalName: 'hoisin sauce',
      canonicalNameTR: 'hoisin sos',
      aliases: ['chinese bbq sauce', 'plum sauce'],
      defaultCategory: 'condiments',
      defaultShelfLifeDays: 365,
    },
    {
      canonicalName: 'sriracha',
      canonicalNameTR: 'sriracha',
      aliases: ['sriracha hot sauce', 'rooster sauce'],
      defaultCategory: 'condiments',
      defaultShelfLifeDays: 365,
    },
    {
      canonicalName: 'pomegranate molasses',
      canonicalNameTR: 'nar ekşisi',
      aliases: ['pomegranate syrup', 'nar pekmezi'],
      defaultCategory: 'condiments',
      defaultShelfLifeDays: 365,
    },
  ];

  // Use createMany with skipDuplicates for idempotent seeding
  const result = await prisma.ingredientCatalog.createMany({
    data: ingredients,
    skipDuplicates: true,
  });

  console.log(`✅ Seeded ${result.count} ingredient catalog entries`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
